--select top 10 * from #dmed
DECLARE

@DTINI CHAR(10),
@DTFIM CHAR(10),
@EMPRESA CHAR(2)

SET @EMPRESA = 'MT'

--AS
-- DROP TABLE #T	DROP TABLE #DMED DROP TABLE #DMED_CONTRAT DROP TABLE #DMED_CONTRAT1 DROP TABLE #DMED_CONTRAT_MENS DROP TABLE #DMED_CONTRAT1_MENS
SET @DTINI = '01/01/2019'
SET @DTFIM = '31/12/2019'
 

--SELECT Valor_Pago,* FROM Receber WHERE CODIGO_CONTRATANTE = 19993 AND Valor_Pago > 0 AND YEAR(DATA_PAGAMENTO) = 2013

SELECT  

    C.NOME AS NM_CONTRATANTE,
	R.TIPO_DOCUMENTO,
    T.DESCRICAO AS DSTPDOCUMENTO,
	R.VALOR_PAGO, 
	R.DATA_PAGAMENTO ,
	R.CODIGO_CONTRATANTE,
	R.CODIGO_USUARIO, 
	ISNULL(R.DTINCLUSAO,DATA_EMISSAO) DTINCLUSAO,
    R.ORCAMENTO,    
    C.CODIGO,
    C.CODIGO AS CD_CONTRATANTE,
    'S' LG_PODE_ALTERAR,
    'N' FLEGAR,
    CAST(NULL AS BIT) lg_ir,
    CAST(NULL AS DATETIME) DATA_INCLUSAO,
    C.INCLUSAO AS DT_INCLUSAO_CONTRAT,
    'M' TIPO,
    cast('' as varchar(50)) MOTIVO

INTO #DMED

FROM 
	RECEBER R, 
	TIPODOCUMENTO T,
    CONTRATANTE C,
    PLANO P

WHERE 
	     T.CODIGO = R.TIPO_DOCUMENTO 
        AND C.CODIGO  = R.CODIGO_CONTRATANTE
        AND P.CODIGO  = C.PLANO
	AND DATA_PAGAMENTO BETWEEN @DTINI AND @DTFIM
	AND VALOR_PAGO > 0 -- SEGUNDO GABI SOMENTE LISTA QUEM PAGOU NO MES..
	AND C.Empresa = 0
    and T.CODIGO IN(select CODIGO from TipoDocumento where Classificacao = 'Mensalidade')
--    and t.codigo in(1,4,9,10,11,14,15,16,18,21,23,26)


INSERT INTO #DMED

SELECT  
    U.NOME AS NM_CONTRATANTE,
    R.TIPO_DOCUMENTO,
    T.DESCRICAO AS DSTPDOCUMENTO,
	R.VALOR_PAGO, 
	R.DATA_PAGAMENTO ,
	R.CODIGO_CONTRATANTE,
	R.CODIGO_USUARIO, 
	ISNULL(R.DTINCLUSAO,DATA_EMISSAO) DTINCLUSAO,
    R.ORCAMENTO,
    U.CODIGO_COMPLETO,
    U.CODIGO AS CD_CONTRATANTE,
    'S' LG_PODE_ALTERAR,
    'N' FLEGAR,
    O.lg_ir,
    U.DATA_INCLUSAO,
    C.INCLUSAO AS DT_INCLUSAO_CONTRAT,
    'O' TIPO,
    '' motivo

 
FROM 
	RECEBER R

INNER JOIN	TIPODOCUMENTO T 
ON
   T.CODIGO = R.TIPO_DOCUMENTO 

INNER JOIN USUARIO U 
ON
   U.CODIGO_COMPLETO = R.CODIGO_USUARIO

INNER JOIN CONTRATANTE C
ON
    C.CODIGO  = U.CODIGO

INNER JOIN ORCAMENTO O
ON
  O.NUMERO = R.ORCAMENTO --TB ORCAMENTO
  

WHERE 
	        
	    DATA_PAGAMENTO BETWEEN @DTINI AND @DTFIM
	AND VALOR_PAGO > 0 -- SEGUNDO GABI SOMENTE LISTA QUEM PAGOU NO MES..
    --AND FIS_JUR = 'Física' -- SEGUNDO GABI ORÇAMENTOS MANUT É O BENEF. QUE PAGA, INTÃO NÃO VERIFICA SE É PJ OU PF
   AND T.CODIGO IN(select CODIGO from TipoDocumento where Classificacao <> 'Mensalidade')    -- orc. e manut)    
   

update #dmed set lg_ir = 0 where lg_ir is null


UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'SOLICITOU RECIBO DE IR' FROM RECIBOIR_CONTRATANTE R WHERE R.CD_CONTRATANTE = #DMED.CD_CONTRATANTE AND R.ANO IN(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,20222)

UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'CONTRATANTE NOVO' WHERE YEAR(DT_INCLUSAO_CONTRAT) >= 2019 and LG_PODE_ALTERAR = 'S'
DELETE FROM #DMED WHERE VALOR_PAGO <= 0.05


--BEGIN TRAN UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'INFORMOU IR NO ORCAMENTO' WHERE lg_ir = 1 and LG_PODE_ALTERAR = 'S' ROLLBACK
select distinct dstpdocumento from #DMED
select top 10 * from orcamento
select * from tipoorcamento
--select dstpdocumento,sum(valor_pago) from #dmed where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N') group by dstpdocumento
select sum(valor_pago) from #dmed where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N') 
-- PROBLEMAS DE ARREDONDAMENTO SQL SEVER (2013 PRECISOU)



select  sum(valor_pago) from #DMED where dstpdocumento = 'MENSALIDADE'
select * from #dmed where nm_contratante = 'enio da silveira'
select * FROM RECIBOIR_CONTRATANTE R WHERE R.CD_CONTRATANTE =  15449 AND R.ANO IN(2010,2011,2012,2013)

select sum(valor_pago) from #dmed where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N')

select sum(valor_pago) from #DMED where DSTPDOCUMENTO <> 'MENSALIDADE' AND LG_PODE_ALTERAR = 'N'

select sum(valor_pago) from #DMED where DSTPDOCUMENTO = 'ORCAMENTO' AND LG_PODE_ALTERAR = 'N'

-- abaixo levantamento com base e-mail gabi de 15/02/2017

-- primeira aba 2020 *Todas as mensalidades

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
--WHERE DSTPDOCUMENTO = 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo = 'M' --OR LG_PODE_ALTERAR = 'N'
GROUP BY Codigo_Contratante,NM_CONTRATANTE ORDER BY NM_CONTRATANTE

-- segunda aba 2020 *Todas as mensalidades que solicitaram ir algum dia

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
--WHERE DSTPDOCUMENTO = 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo = 'M' --OR LG_PODE_ALTERAR = 'N'
and MOTIVO = 'SOLICITOU RECIBO DE IR'
GROUP BY Codigo_Contratante,NM_CONTRATANTE ORDER BY NM_CONTRATANTE


-- terceira aba 2020 *Todos tratamento(orçamento) 

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
WHERE DSTPDOCUMENTO = 'ORCAMENTO' --OR LG_PODE_ALTERAR = 'N'
GROUP BY Codigo_Contratante,NM_CONTRATANTE
ORDER BY valor desc

-- quarta aba 2020 *Todos tratamento(orçamento) que solicitaram IR

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
WHERE DSTPDOCUMENTO = 'ORCAMENTO' --OR LG_PODE_ALTERAR = 'N'

and MOTIVO = 'SOLICITOU RECIBO DE IR'
GROUP BY Codigo_Contratante,NM_CONTRATANTE
ORDER BY valor desc

-- quinta aba 2020 *Todos tratamento(orçamento) contratantes novos

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
WHERE DSTPDOCUMENTO = 'ORCAMENTO' --OR LG_PODE_ALTERAR = 'N'

and MOTIVO = 'CONTRATANTE NOVO'
GROUP BY Codigo_Contratante,NM_CONTRATANTE
ORDER BY valor desc

-- e-mail do dia 28/01/20 12:11

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR, motivo FROM #DMED
WHERE DSTPDOCUMENTO = 'ORCAMENTO' --OR LG_PODE_ALTERAR = 'N'

and MOTIVO not in ('SOLICITOU RECIBO DE IR','CONTRATANTE NOVO')
GROUP BY Codigo_Contratante,NM_CONTRATANTE,motivo
ORDER BY valor desc



-- sexta aba 2020 *manutenção total

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
WHERE DSTPDOCUMENTO = 'MANUTENCAO' --OR LG_PODE_ALTERAR = 'N'
GROUP BY Codigo_Contratante,NM_CONTRATANTE
ORDER BY valor desc

-- setima aba 2020 *Manutenção T que solicitou IR

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
WHERE DSTPDOCUMENTO = 'MANUTENCAO' --OR LG_PODE_ALTERAR = 'N'

and MOTIVO = 'SOLICITOU RECIBO DE IR'
GROUP BY Codigo_Contratante,NM_CONTRATANTE
ORDER BY valor desc

-- Oitava aba 2020 *Manutenção contrantante novo

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
WHERE DSTPDOCUMENTO = 'MANUTENCAO' --OR LG_PODE_ALTERAR = 'N'

and MOTIVO = 'CONTRATANTE NOVO'
GROUP BY Codigo_Contratante,NM_CONTRATANTE
ORDER BY valor desc
