--select top 10 * from #dmed
DECLARE

@DTINI CHAR(10),
@DTFIM CHAR(10),
@EMPRESA CHAR(2)

SET @EMPRESA = 'MT'

--AS
-- DROP TABLE #T	DROP TABLE #DMED DROP TABLE #DMED_CONTRAT DROP TABLE #DMED_CONTRAT1 DROP TABLE #DMED_CONTRAT_MENS DROP TABLE #DMED_CONTRAT1_MENS
SET @DTINI = '01/01/2016'
SET @DTFIM = '31/12/2016'
 

--SELECT Valor_Pago,* FROM Receber WHERE CODIGO_CONTRATANTE = 19993 AND Valor_Pago > 0 AND YEAR(DATA_PAGAMENTO) = 2013

SELECT  

    C.NOME AS NM_CONTRATANTE,
	R.TIPO_DOCUMENTO,
    T.DESCRICAO AS DSTPDOCUMENTO,
	R.VALOR_PAGO, 
	R.DATA_PAGAMENTO ,
	R.CODIGO_CONTRATANTE,
	R.CODIGO_USUARIO, 
	ISNULL(R.DTINCLUSAO,DATA_EMISSAO) DTINCLUSAO,
    R.ORCAMENTO,    
    C.CODIGO,
    C.CODIGO AS CD_CONTRATANTE,
    'S' LG_PODE_ALTERAR,
    'N' FLEGAR,
    CAST(NULL AS BIT) lg_ir,
    CAST(NULL AS DATETIME) DATA_INCLUSAO,
    C.INCLUSAO AS DT_INCLUSAO_CONTRAT,
    'M' TIPO,
    cast('' as varchar(50)) MOTIVO

INTO #DMED

FROM 
	RECEBER R, 
	TIPODOCUMENTO T,
    CONTRATANTE C,
    PLANO P

WHERE 
	     T.CODIGO = R.TIPO_DOCUMENTO 
        AND C.CODIGO  = R.CODIGO_CONTRATANTE
        AND P.CODIGO  = C.PLANO
	AND DATA_PAGAMENTO BETWEEN @DTINI AND @DTFIM
	AND VALOR_PAGO > 0 -- SEGUNDO GABI SOMENTE LISTA QUEM PAGOU NO MES..
	AND C.Empresa = 0
    and T.CODIGO IN(select CODIGO from TipoDocumento where Classificacao = 'Mensalidade')
--    and t.codigo in(1,4,9,10,11,14,15,16,18,21,23,26)


INSERT INTO #DMED

SELECT  
    U.NOME AS NM_CONTRATANTE,
    R.TIPO_DOCUMENTO,
    T.DESCRICAO AS DSTPDOCUMENTO,
	R.VALOR_PAGO, 
	R.DATA_PAGAMENTO ,
	R.CODIGO_CONTRATANTE,
	R.CODIGO_USUARIO, 
	ISNULL(R.DTINCLUSAO,DATA_EMISSAO) DTINCLUSAO,
    R.ORCAMENTO,
    U.CODIGO_COMPLETO,
    U.CODIGO AS CD_CONTRATANTE,
    'S' LG_PODE_ALTERAR,
    'N' FLEGAR,
    O.lg_ir,
    U.DATA_INCLUSAO,
    C.INCLUSAO AS DT_INCLUSAO_CONTRAT,
    'O' TIPO,
    '' motivo

 
FROM 
	RECEBER R

INNER JOIN	TIPODOCUMENTO T 
ON
   T.CODIGO = R.TIPO_DOCUMENTO 

INNER JOIN USUARIO U 
ON
   U.CODIGO_COMPLETO = R.CODIGO_USUARIO

INNER JOIN CONTRATANTE C
ON
    C.CODIGO  = U.CODIGO

INNER JOIN ORCAMENTO O
ON
  O.NUMERO = R.ORCAMENTO --TB ORCAMENTO
  

WHERE 
	        
	    DATA_PAGAMENTO BETWEEN @DTINI AND @DTFIM
	AND VALOR_PAGO > 0 -- SEGUNDO GABI SOMENTE LISTA QUEM PAGOU NO MES..
    --AND FIS_JUR = 'Física' -- SEGUNDO GABI ORÇAMENTOS MANUT É O BENEF. QUE PAGA, INTÃO NÃO VERIFICA SE É PJ OU PF
   AND T.CODIGO IN(select CODIGO from TipoDocumento where Classificacao <> 'Mensalidade')    -- orc. e manut)    
   

update #dmed set lg_ir = 0 where lg_ir is null


UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'SOLICITOU RECIBO DE IR' FROM RECIBOIR_CONTRATANTE R WHERE R.CD_CONTRATANTE = #DMED.CD_CONTRATANTE AND R.ANO IN(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020)

UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'CONTRATANTE NOVO' WHERE YEAR(DT_INCLUSAO_CONTRAT) >= 2016 and LG_PODE_ALTERAR = 'S'
--BEGIN TRAN UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'INFORMOU IR NO ORCAMENTO' WHERE lg_ir = 1 and LG_PODE_ALTERAR = 'S' ROLLBACK
select * from #DMED
--select dstpdocumento,sum(valor_pago) from #dmed where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N') group by dstpdocumento
select sum(valor_pago) from #dmed where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N') 
-- PROBLEMAS DE ARREDONDAMENTO SQL SEVER (2013 PRECISOU)

DELETE FROM #DMED WHERE VALOR_PAGO <= 0.05
select  sum(valor_pago) from #DMED where dstpdocumento = 'MENSALIDADE'
select * from #dmed where nm_contratante = 'enio da silveira'
select * FROM RECIBOIR_CONTRATANTE R WHERE R.CD_CONTRATANTE =  15449 AND R.ANO IN(2010,2011,2012,2013)

select sum(valor_pago) from #dmed where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N')

select sum(valor_pago) from #DMED where DSTPDOCUMENTO <> 'MENSALIDADE' AND LG_PODE_ALTERAR = 'N'

select sum(valor_pago) from #DMED where DSTPDOCUMENTO = 'ORCAMENTO' AND LG_PODE_ALTERAR = 'N'

-- abaixo levantamento com base e-mail gabi de 15/02/2017

-- primeira aba do levantamento inicial 2017 746.623,00

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
--WHERE DSTPDOCUMENTO = 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo = 'M' --OR LG_PODE_ALTERAR = 'N'
GROUP BY Codigo_Contratante,NM_CONTRATANTE ORDER BY NM_CONTRATANTE
-- segunda aba 2017
SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,LG_PODE_ALTERAR,MOTIVO FROM #DMED
--WHERE DSTPDOCUMENTO <> 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo <> 'M' --and LG_PODE_ALTERAR = 'S'
and MOTIVO = 'SOLICITOU RECIBO DE IR'
GROUP BY Codigo_Contratante,NM_CONTRATANTE,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc

-- terceira aba 2017

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,LG_PODE_ALTERAR,MOTIVO FROM #DMED
--WHERE DSTPDOCUMENTO <> 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo <> 'M' --and LG_PODE_ALTERAR = 'S'
and MOTIVO = 'CONTRATANTE NOVO'
GROUP BY Codigo_Contratante,NM_CONTRATANTE,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc



--quarta aba
SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
--WHERE DSTPDOCUMENTO <> 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE motivo = '' and tipo <> 'M' --and LG_PODE_ALTERAR = 'S'

GROUP BY Codigo_Contratante,NM_CONTRATANTE ORDER BY valor desc

-- quinta aba
SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
--WHERE DSTPDOCUMENTO <> 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo <> 'M' --and LG_PODE_ALTERAR = 'S'

GROUP BY Codigo_Contratante,NM_CONTRATANTE ORDER BY valor desc



-- primeira aba do levantamento inicial 2016
SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,DSTPDOCUMENTO,LG_PODE_ALTERAR,MOTIVO,TIPO FROM #DMED
--WHERE DSTPDOCUMENTO = 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo = 'M' --OR LG_PODE_ALTERAR = 'N'
GROUP BY Codigo_Contratante,NM_CONTRATANTE,TIPO,DSTPDOCUMENTO,LG_PODE_ALTERAR,MOTIVO ORDER BY NM_CONTRATANTE
-- segunda aba 2016
SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,DSTPDOCUMENTO,LG_PODE_ALTERAR,MOTIVO,TIPO FROM #DMED
--WHERE DSTPDOCUMENTO <> 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo <> 'M' --and LG_PODE_ALTERAR = 'S'
GROUP BY Codigo_Contratante,NM_CONTRATANTE,TIPO,DSTPDOCUMENTO,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc





SELECT sum(valor_pago) FROM #DMED WHERE DSTPDOCUMENTO = 'ORCAMENTO' and LG_PODE_ALTERAR = 'S' and codigo_contratante in(23129,17592,23608,24935,18989,25614,16036,12664,20802,10903,19305,25667,24381,18006,25696,22193,22689,17592,24955,8124 ,11960,7804 ,18895,11032,22707,24668)
and nm_contratante in('ALEXANDRE CORREA DE LACERDA','LAURINDO VINHAS RIBEIRO','ANIVALDO GERALDO ALVES PEREIRA FERREIRA','CARLOS ALBERTO COTRIM','GENI CANDIDA DOS SANTOS SILVA','IVONICE NEVES GONVALVES','DIVA NICOLUSSI DA SILVA','APARECIDA DINA CALEFFI ANDRIÃO','MARLI MARIA GONÇALVES FARIA','RIVALDO CARNELOSSI','MARIA APARECIDA GELFUSO PIRES','RENATA ANDREIA GOMES','JOANA DARC TOMAZ COUTIELINO','FATIMA DE JESUS SILVA RIPOLI ','MARIA AMELIA GARCIA FERREIRA ','ILDA COSTA DOS SANTOS','MARCELO PIRONELLI ','RODRIGO CARLOS RODOWCIZ','CLEONICE CADURIN CUSTODIA','SILVANA MERLO A.BENTO','REGINA CELIA BALDOCHI MARCOLIN','APARECIDO DOS SANTOS','HAMILTON CESAR CORDEIRO','ADAILTON NASCIMENTO ARAUJO OLIVEIRA','MARIA APARECIDA BARBOSA DA SILVA','CARLOS FERNANDO PEREIRA')
GROUP BY Codigo_Contratante,NM_CONTRATANTE,DSTPDOCUMENTO,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc



SELECT TOP 26 Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,DSTPDOCUMENTO,LG_PODE_ALTERAR,MOTIVO into #selGabi FROM #DMED
WHERE DSTPDOCUMENTO = 'ORCAMENTO' and LG_PODE_ALTERAR = 'S'
and codigo_contratante in(23129,17592,23608,24935,18989,25614,16036,12664,20802,10903,19305,25667,24381,18006,25696,22193,22689,17592,24955,8124 ,11960,7804 ,18895,11032,22707,24668)
GROUP BY Codigo_Contratante,NM_CONTRATANTE,DSTPDOCUMENTO,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc


SELECT SUM(VALOR_PAGO) FROM #DMED WHERE DSTPDOCUMENTO = 'MENSALIDADE'
--select sum(valor_pago) from #DMED where  LG_PODE_ALTERAR = 'N'
select Codigo_Contratante,nm_contratante,dstpdocumento,sum(valor_pago) valor_pago,MOTIVO from #DMED where  LG_PODE_ALTERAR = 'S' 
group by Codigo_Contratante,nm_contratante,dstpdocumento,MOTIVO
order by Valor_Pago desc




-- ENVIA TODA AS MENSALIDADES
---insert into contrat_dmed select 2013,codigo_contratante,'M',SUM(valor_pago), 'TODAS AS MENSALIDADES' from #DMED where DSTPDOCUMENTO = 'MENSALIDADE' GROUP BY Codigo_Contratante
insert into contrat_dmed select 2013,codigo_contratante,'M',SUM(valor_pago), 'TODAS AS MENSALIDADES' from #DMED where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N') GROUP BY Codigo_Contratante
SELECT obs,SUM(VALOR) FROM CONTRAT_DMED A WHERE A.ANO = 2013 group by obs
SELECT SUM(VALOR) FROM CONTRAT_DMED A WHERE A.ANO = 2013
SELECT top 10 * FROM CONTRAT_DMED A WHERE A.ANO = 2013
-- ENVIA TODOS ORC QUE OU SÃO NOVOS OU QUE SOLICITARAM IR

insert into contrat_dmed select 2013,codigo_contratante,'O',SUM(valor_pago), 'CONTRAT NOVOS OU QUE SOLICITOU IR' FROM #DMED WHERE DSTPDOCUMENTO = 'ORCAMENTO' AND LG_PODE_ALTERAR = 'N' GROUP BY Codigo_Contratante
--insert into contrat_dmed select 2013,codigo_contratante,'O',SUM(valor_pago), 'CONTRAT NOVOS OU QUE SOLICITOU IR' FROM #DMED where DSTPDOCUMENTO <> 'MENSALIDADE' AND LG_PODE_ALTERAR = 'N' GROUP BY Codigo_Contratante

insert into contrat_dmed select 2013,codigo_contratante,'O',SUM(valor), 'ORCAMENTOS SEL GABI' FROM #selGabi WHERE DSTPDOCUMENTO = 'ORCAMENTO' and LG_PODE_ALTERAR = 'S'
and codigo_contratante in(23129,17592,23608,24935,18989,25614,16036,12664,20802,10903,19305,25667,24381,18006,25696,22193,22689,17592,24955,8124 ,11960,7804 ,18895,11032,22707,24668) GROUP BY Codigo_Contratante


select * from #selgabi


--SELECT SUM(VALOR) FROM  CONTRAT_DMED WHERE ANO = 2013


--- lista por tipo de documento para analise
--SELECT MOTIVO,DSTPDOCUMENTO, replace(str(SUM(VALOR_PAGO),10,2),'.',',') vr_pago FROM #DMED WHERE LG_PODE_ALTERAR = 'N' group by DSTPDOCUMENTO,motivo order by 1,2



-- LISTA AGRUPADO POR MENSALIDADE/ORCAMENTO
--SELECT TIPO, replace(str(SUM(VALOR_PAGO),10,2),'.',',') vr_pago FROM #DMED  GROUP BY TIPO

--SELECT TIPO, replace(str(SUM(VALOR_PAGO),10,2),'.',',')  vr_pago FROM #DMED WHERE LG_PODE_ALTERAR = 'N'  GROUP BY TIPO

--SELECT TOP 10 * FROM #DMED SELECT DISTINCT DSTPDOCUMENTO FROM #DMED
/*
SELECT 
    CGC_CPF,
    DT_NASCIMENTO,
    LG_TITULAR,

CODIGO_CONTRATANTE, SUM(Valor_Pago) AS VALOR_PAGO, MOTIVO FROM #DMED 
WHERE TIPO = 'O' --LG_PODE_ALTERAR = 'S'  
GROUP BY 
    CGC_CPF,
    DT_NASCIMENTO,
    LG_TITULAR,
CODIGO_CONTRATANTE , MOTIVO ORDER BY 2 DESC


SELECT SUM(Valor_Pago) AS VALOR_PAGO FROM #DMED WHERE LG_PODE_ALTERAR is null 'N' 

select * from contratante where Codigo in(5071,17923,22337)
*/