--select top 10 * from #dmed
DECLARE

@DTINI CHAR(10),
@DTFIM CHAR(10),
@EMPRESA CHAR(2)

SET @EMPRESA = 'MT'

--AS
-- DROP TABLE #T	DROP TABLE #DMED DROP TABLE #DMED_CONTRAT DROP TABLE #DMED_CONTRAT1 DROP TABLE #DMED_CONTRAT_MENS DROP TABLE #DMED_CONTRAT1_MENS
SET @DTINI = '01/01/2017'
SET @DTFIM = '31/12/2017'
 

--SELECT Valor_Pago,* FROM Receber WHERE CODIGO_CONTRATANTE = 19993 AND Valor_Pago > 0 AND YEAR(DATA_PAGAMENTO) = 2013

SELECT  

    C.NOME AS NM_CONTRATANTE,
	R.TIPO_DOCUMENTO,
    T.DESCRICAO AS DSTPDOCUMENTO,
	R.VALOR_PAGO, 
	R.DATA_PAGAMENTO ,
	R.CODIGO_CONTRATANTE,
	R.CODIGO_USUARIO, 
	ISNULL(R.DTINCLUSAO,DATA_EMISSAO) DTINCLUSAO,
    R.ORCAMENTO,    
    C.CODIGO,
    C.CODIGO AS CD_CONTRATANTE,
    'S' LG_PODE_ALTERAR,
    'N' FLEGAR,
    CAST(NULL AS BIT) lg_ir,
    CAST(NULL AS DATETIME) DATA_INCLUSAO,
    C.INCLUSAO AS DT_INCLUSAO_CONTRAT,
    'M' TIPO,
    cast('' as varchar(50)) MOTIVO

INTO #DMED

FROM 
	RECEBER R, 
	TIPODOCUMENTO T,
    CONTRATANTE C,
    PLANO P

WHERE 
	     T.CODIGO = R.TIPO_DOCUMENTO 
        AND C.CODIGO  = R.CODIGO_CONTRATANTE
        AND P.CODIGO  = C.PLANO
	AND DATA_PAGAMENTO BETWEEN @DTINI AND @DTFIM
	AND VALOR_PAGO > 0 -- SEGUNDO GABI SOMENTE LISTA QUEM PAGOU NO MES..
	AND C.Empresa = 0
    and T.CODIGO IN(select CODIGO from TipoDocumento where Classificacao = 'Mensalidade')
--    and t.codigo in(1,4,9,10,11,14,15,16,18,21,23,26)


INSERT INTO #DMED

SELECT  
    U.NOME AS NM_CONTRATANTE,
    R.TIPO_DOCUMENTO,
    T.DESCRICAO AS DSTPDOCUMENTO,
	R.VALOR_PAGO, 
	R.DATA_PAGAMENTO ,
	R.CODIGO_CONTRATANTE,
	R.CODIGO_USUARIO, 
	ISNULL(R.DTINCLUSAO,DATA_EMISSAO) DTINCLUSAO,
    R.ORCAMENTO,
    U.CODIGO_COMPLETO,
    U.CODIGO AS CD_CONTRATANTE,
    'S' LG_PODE_ALTERAR,
    'N' FLEGAR,
    O.lg_ir,
    U.DATA_INCLUSAO,
    C.INCLUSAO AS DT_INCLUSAO_CONTRAT,
    'O' TIPO,
    '' motivo

 
FROM 
	RECEBER R

INNER JOIN	TIPODOCUMENTO T 
ON
   T.CODIGO = R.TIPO_DOCUMENTO 

INNER JOIN USUARIO U 
ON
   U.CODIGO_COMPLETO = R.CODIGO_USUARIO

INNER JOIN CONTRATANTE C
ON
    C.CODIGO  = U.CODIGO

INNER JOIN ORCAMENTO O
ON
  O.NUMERO = R.ORCAMENTO --TB ORCAMENTO
  

WHERE 
	        
	    DATA_PAGAMENTO BETWEEN @DTINI AND @DTFIM
	AND VALOR_PAGO > 0 -- SEGUNDO GABI SOMENTE LISTA QUEM PAGOU NO MES..
    --AND FIS_JUR = 'Física' -- SEGUNDO GABI ORÇAMENTOS MANUT É O BENEF. QUE PAGA, INTÃO NÃO VERIFICA SE É PJ OU PF
   AND T.CODIGO IN(select CODIGO from TipoDocumento where Classificacao <> 'Mensalidade')    -- orc. e manut)    
   

update #dmed set lg_ir = 0 where lg_ir is null


UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'SOLICITOU RECIBO DE IR' FROM RECIBOIR_CONTRATANTE R WHERE R.CD_CONTRATANTE = #DMED.CD_CONTRATANTE AND R.ANO IN(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020)

UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'CONTRATANTE NOVO' WHERE YEAR(DT_INCLUSAO_CONTRAT) >= 2017 and LG_PODE_ALTERAR = 'S'
--BEGIN TRAN UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'INFORMOU IR NO ORCAMENTO' WHERE lg_ir = 1 and LG_PODE_ALTERAR = 'S' ROLLBACK
select distinct dstpdocumento from #DMED
select top 10 * from orcamento
select * from tipoorcamento
--select dstpdocumento,sum(valor_pago) from #dmed where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N') group by dstpdocumento
select sum(valor_pago) from #dmed where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N') 
-- PROBLEMAS DE ARREDONDAMENTO SQL SEVER (2013 PRECISOU)

DELETE FROM #DMED WHERE VALOR_PAGO <= 0.05

select  sum(valor_pago) from #DMED where dstpdocumento = 'MENSALIDADE'
select * from #dmed where nm_contratante = 'enio da silveira'
select * FROM RECIBOIR_CONTRATANTE R WHERE R.CD_CONTRATANTE =  15449 AND R.ANO IN(2010,2011,2012,2013)

select sum(valor_pago) from #dmed where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N')

select sum(valor_pago) from #DMED where DSTPDOCUMENTO <> 'MENSALIDADE' AND LG_PODE_ALTERAR = 'N'

select sum(valor_pago) from #DMED where DSTPDOCUMENTO = 'ORCAMENTO' AND LG_PODE_ALTERAR = 'N'

-- abaixo levantamento com base e-mail gabi de 15/02/2017

-- primeira aba 2018 do levantamento inicial 2018 779.002,60

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
--WHERE DSTPDOCUMENTO = 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo = 'M' --OR LG_PODE_ALTERAR = 'N'
GROUP BY Codigo_Contratante,NM_CONTRATANTE ORDER BY NM_CONTRATANTE

-- segunda aba 2018 2 – todas as mensalidades de todos que ja foram pra algum dmed + contratos de 2017
SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,LG_PODE_ALTERAR,MOTIVO FROM #DMED
--WHERE DSTPDOCUMENTO <> 'MENSALIDADE' --OR LG_PODE_ALTERAR = 'N'
WHERE tipo <> 'M' --and LG_PODE_ALTERAR = 'S'
and MOTIVO in('SOLICITOU RECIBO DE IR','CONTRATANTE NOVO')
GROUP BY Codigo_Contratante,NM_CONTRATANTE,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc


-- terceira aba 2018 3 – todos os tratamentos (só orçamento) lembrar que tem tipo 01 e 10(aqui pegar dstpidocumetno = orcamento

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,LG_PODE_ALTERAR,MOTIVO FROM #DMED
WHERE DSTPDOCUMENTO = 'ORCAMENTO' --OR LG_PODE_ALTERAR = 'N'
-- gabi passou e-mail 26012018 solicitando o criterio
and not MOTIVO in('SOLICITOU RECIBO DE IR','CONTRATANTE NOVO')
GROUP BY Codigo_Contratante,NM_CONTRATANTE,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc

--quarta aba 2018 3 – todos os tratamentos (só orçamento) lembrar que tem tipo 01 e 10

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,LG_PODE_ALTERAR,MOTIVO FROM #DMED
WHERE DSTPDOCUMENTO = 'ORCAMENTO' --OR LG_PODE_ALTERAR = 'N'
and MOTIVO in('SOLICITOU RECIBO DE IR','CONTRATANTE NOVO')
GROUP BY Codigo_Contratante,NM_CONTRATANTE,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc

-- QUINTA  aba 2018 3 – todas as manutenções de aparelho

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR FROM #DMED
WHERE DSTPDOCUMENTO = 'MANUTENCAO' --OR LG_PODE_ALTERAR = 'N'
GROUP BY Codigo_Contratante,NM_CONTRATANTE,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc

--SEXTA aba 2018 todas as manutenções de aparelho de quem já foram para algum dmed + contratos de 201

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,LG_PODE_ALTERAR,MOTIVO FROM #DMED
WHERE DSTPDOCUMENTO = 'MANUTENCAO' --OR LG_PODE_ALTERAR = 'N'
and MOTIVO in('SOLICITOU RECIBO DE IR','CONTRATANTE NOVO')
GROUP BY Codigo_Contratante,NM_CONTRATANTE,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc

--SETIMA ABA TODAS AS MANUTENÇÕES EXCETO NOVOS E IR

SELECT Codigo_Contratante,NM_CONTRATANTE,SUM(VALOR_PAGO) VALOR,LG_PODE_ALTERAR,MOTIVO FROM #DMED
WHERE DSTPDOCUMENTO = 'ORCAMENTO' --OR LG_PODE_ALTERAR = 'N'
and MOTIVO NOT in('SOLICITOU RECIBO DE IR','CONTRATANTE NOVO')
GROUP BY Codigo_Contratante,NM_CONTRATANTE,LG_PODE_ALTERAR,MOTIVO ORDER BY valor desc

SELECT SUM(VALOR_PAGO) VALOR FROM #DMED
WHERE DSTPDOCUMENTO = 'ORCAMENTO' --OR LG_PODE_ALTERAR = 'N'
and MOTIVO NOT in('SOLICITOU RECIBO DE IR','CONTRATANTE NOVO')


-- ENVIA TODA AS MENSALIDADES
---insert into contrat_dmed select 2013,codigo_contratante,'M',SUM(valor_pago), 'TODAS AS MENSALIDADES' from #DMED where DSTPDOCUMENTO = 'MENSALIDADE' GROUP BY Codigo_Contratante
insert into contrat_dmed select 2013,codigo_contratante,'M',SUM(valor_pago), 'TODAS AS MENSALIDADES' from #DMED where DSTPDOCUMENTO = 'MENSALIDADE' OR (DSTPDOCUMENTO in('ACORDO','INCLUSAO ESCRITORIO','EMERGENCIA','ACORDO ADVOGADO','INCLUSAO USUARIOS','CARTEIRINHAS','CARTAO VENDEDOR(A)','MANUTENCAO') AND LG_PODE_ALTERAR = 'N') GROUP BY Codigo_Contratante
SELECT obs,SUM(VALOR) FROM CONTRAT_DMED A WHERE A.ANO = 2013 group by obs
SELECT SUM(VALOR) FROM CONTRAT_DMED A WHERE A.ANO = 2013
SELECT top 10 * FROM CONTRAT_DMED A WHERE A.ANO = 2013
-- ENVIA TODOS ORC QUE OU SÃO NOVOS OU QUE SOLICITARAM IR

insert into contrat_dmed select 2013,codigo_contratante,'O',SUM(valor_pago), 'CONTRAT NOVOS OU QUE SOLICITOU IR' FROM #DMED WHERE DSTPDOCUMENTO = 'ORCAMENTO' AND LG_PODE_ALTERAR = 'N' GROUP BY Codigo_Contratante
--insert into contrat_dmed select 2013,codigo_contratante,'O',SUM(valor_pago), 'CONTRAT NOVOS OU QUE SOLICITOU IR' FROM #DMED where DSTPDOCUMENTO <> 'MENSALIDADE' AND LG_PODE_ALTERAR = 'N' GROUP BY Codigo_Contratante

insert into contrat_dmed select 2013,codigo_contratante,'O',SUM(valor), 'ORCAMENTOS SEL GABI' FROM #selGabi WHERE DSTPDOCUMENTO = 'ORCAMENTO' and LG_PODE_ALTERAR = 'S'
and codigo_contratante in(23129,17592,23608,24935,18989,25614,16036,12664,20802,10903,19305,25667,24381,18006,25696,22193,22689,17592,24955,8124 ,11960,7804 ,18895,11032,22707,24668) GROUP BY Codigo_Contratante




--SELECT SUM(VALOR) FROM  CONTRAT_DMED WHERE ANO = 2013


--- lista por tipo de documento para analise
--SELECT MOTIVO,DSTPDOCUMENTO, replace(str(SUM(VALOR_PAGO),10,2),'.',',') vr_pago FROM #DMED WHERE LG_PODE_ALTERAR = 'N' group by DSTPDOCUMENTO,motivo order by 1,2



-- LISTA AGRUPADO POR MENSALIDADE/ORCAMENTO
--SELECT TIPO, replace(str(SUM(VALOR_PAGO),10,2),'.',',') vr_pago FROM #DMED  GROUP BY TIPO

--SELECT TIPO, replace(str(SUM(VALOR_PAGO),10,2),'.',',')  vr_pago FROM #DMED WHERE LG_PODE_ALTERAR = 'N'  GROUP BY TIPO

--SELECT TOP 10 * FROM #DMED SELECT DISTINCT DSTPDOCUMENTO FROM #DMED
/*
SELECT 
    CGC_CPF,
    DT_NASCIMENTO,
    LG_TITULAR,

CODIGO_CONTRATANTE, SUM(Valor_Pago) AS VALOR_PAGO, MOTIVO FROM #DMED 
WHERE TIPO = 'O' --LG_PODE_ALTERAR = 'S'  
GROUP BY 
    CGC_CPF,
    DT_NASCIMENTO,
    LG_TITULAR,
CODIGO_CONTRATANTE , MOTIVO ORDER BY 2 DESC


SELECT SUM(Valor_Pago) AS VALOR_PAGO FROM #DMED WHERE LG_PODE_ALTERAR is null 'N' 

select * from contratante where Codigo in(5071,17923,22337)
*/