program Multi;

{%ToDo 'Multi.todo'}

uses
  dialogs,
  Forms,
  Fundo in 'Fundo.pas' {FormFundo},
  Senha in 'Senha.pas' {FormSenha},
  Seletor in 'Seletor.pas' {FormSeletor},
  Cadastro in 'Cadastro.pas' {FormDiversos},
  Contratante in 'Contratante.pas' {FormContratante},
  VerificaDigito in 'VerificaDigito.pas' {FormVerificaDigito},
  Representantes in 'Representantes.pas' {FormRepresentantes},
  Vendedores in 'Vendedores.pas' {FormVendedores},
  BaixaBanco in 'BaixaBanco.pas' {FormBaixaTitulo},
  Faturamento in 'Faturamento.pas' {FormFaturamento},
  TituloReceber in 'TituloReceber.pas' {FormTituloReceber},
  Francesa in 'Francesa.pas' {FormFrancesa},
  GeraReceber in 'GeraReceber.pas' {FormGeraReceber},
  Fornecedor in 'Fornecedor.pas' {FormFornecedor},
  Informacoes in 'Informacoes.pas' {FormInformacoes},
  QRFaturamentoManutencao in 'QRFaturamentoManutencao.pas' {QRListaFaturamentoManutencao: TQuickRep},
  Volume in 'Volume.pas' {FormVolume},
  TipoOperacaoDebito in 'TipoOperacaoDebito.pas' {FormTipoOperacao},
  QRRetorno in 'QRRetorno.pas' {QRListaRetorno: TQuickRep},
  CadastroTitulares in 'CadastroTitulares.pas' {FormCadastroTitulares},
  CoberturaProcedimento in 'CoberturaProcedimento.pas' {FormCoberturaProcedimento},
  Orcamentos in 'Orcamentos.pas' {FormOrcamentos},
  PesquisaServicos in 'PesquisaServicos.pas' {FormPesquisaServicos},
  Prestacoes in 'Prestacoes.pas' {FormPrestacoes},
  PesquisaClinica in 'PesquisaClinica.pas' {FormPesquisaClinica},
  Odontograma in 'Odontograma.pas' {FormOdontograma},
  EmImpres in 'Emimpres.pas' {FormEmImpressao},
  MensagemAtraso in 'MensagemAtraso.pas' {FormMensagemAtraso},
  RelatoPagar in 'RelatoPagar.pas' {FormRelatoriosPagar},
  QRContratoCobranca in 'QRContratoCobranca.pas' {QRListaContratosCobranca: TQuickRep},
  QRAbeCliVenOrc in 'QRAbeCliVenOrc.pas' {QRTitAbeCliVencOrc: TQuickRep},
  QRBaiForCusto in 'QRBaiForCusto.pas' {QRTitBaiFornCusto: TQuickRep},
  QRAbeForVen in 'QRAbeForVen.pas' {QRTitAbeForVencimento: TQuickRep},
  QRBaiChequePre in 'QRBaiChequePre.pas' {QRTitBaiChequePre: TQuickRep},
  QRBaiCliVenSint in 'QRBaiCliVenSint.pas' {QRTitBaiCliVencimentoSint: TQuickRep},
  QRBaiFor in 'QRBaiFor.pas' {QRTitBaiFornecedor: TQuickRep},
  QRBaiForVen in 'QRBaiForVen.pas' {QRTitBaiForVencimento: TQuickRep},
  QRCanCli in 'QRCanCli.pas' {QRTitCanCliente: TQuickRep},
  QRCanCliVen in 'QRCanCliVen.pas' {QRTitCanCliVencimento: TQuickRep},
  QRCanFor in 'QRCanFor.pas' {QRTitCanFornecedor: TQuickRep},
  QRCanForVen in 'QRCanForVen.pas' {QRTitCanForVencimento: TQuickRep},
  QRAbeGrupo in 'QRAbeGrupo.pas' {QRTitAbeGrupoContr: TQuickRep},
  TituloPagos in 'TituloPagos.pas' {FormTituloPagos},
  ConsultaTitulos in 'ConsultaTitulos.pas' {FormConsultaReceber},
  PesquisaContratante in 'PesquisaContratante.pas' {FormPesquisaContratante},
  ImpressaoOrcamentos in 'ImpressaoOrcamentos.pas' {FormImpressaoOrcamento},
  PesquisaUsuario in 'PesquisaUsuario.pas' {FormPesquisaUsuarios},
  DadosCadastrais in 'DadosCadastrais.pas' {FormDadosCadastrais},
  VisualizaTitulos in 'VisualizaTitulos.pas' {FormVisualizaTitulos},
  ConsultaOrcamentos in 'ConsultaOrcamentos.pas' {FormConsultaOrcamentos},
  TituloBaixados in 'TituloBaixados.pas' {FormTituloBaixados},
  ValorProcedimento in 'ValorProcedimento.pas' {FormValorProcedimento},
  QRValorProcedimento in 'QRValorProcedimento.pas' {QRListaValorProcedimento: TQuickRep},
  TabPrecoXPlano in 'TabPrecoXPlano.pas' {FormTabPrecoxPlano},
  Usuarios in 'Usuarios.pas' {FormUsuarios},
  Servicos in 'Servicos.pas' {FormServicos},
  QRServicos in 'QRServicos.pas' {QRListaServicos: TQuickRep},
  QRVendasPeriodoSintetico in 'QRVendasPeriodoSintetico.pas' {QRListaVendasPeriodoSintetico: TQuickRep},
  RelVendas in 'RelVendas.pas' {FormRelVendas},
  RelComissao in 'RelComissao.pas' {FmRelComissao},
  Desabilita in 'Desabilita.pas' {FormDesabilita},
  Preferencias in 'Preferencias.pas' {FormPreferencias},
  Filtro in 'Filtro.pas' {FormFiltro},
  Dentistas in 'Dentistas.pas' {FormDentistas},
  Proteticos in 'Proteticos.pas' {FormProteticos},
  RelProcedimentosPagos in 'RelProcedimentosPagos.pas' {FormRelProcedimentosPagos},
  QROrcamentosSip in 'QROrcamentosSip.pas' {QRListaOrcamentosSip: TQuickRep},
  Manutencao in 'Manutencao.pas' {FormManutencoes},
  QRAbeCompleto in 'QRAbeCompleto.pas' {QRTitAbeCompleto: TQuickRep},
  PesquisaGrupoCCusto in 'PesquisaGrupoCCusto.pas' {FormPesquisaGrupoCCusto},
  PesquisaVendedor in 'PesquisaVendedor.pas' {FormPesquisaVendedor},
  QRPrecoPlano in 'QRPrecoPlano.pas' {QRListaPrecoPlano: TQuickRep},
  EtiquetaContratante in 'EtiquetaContratante.pas' {FormEtiquetaContratante},
  QRManutencaoNovo in 'QRManutencaoNovo.pas' {QRListaManutencaoNovo: TQuickRep},
  Etiquetas in 'Etiquetas.pas' {FormEtiquetas},
  EtiquetasDentista in 'EtiquetasDentista.pas' {FormEtiquetasDentistas},
  EtiquetasProteticos in 'EtiquetasProteticos.pas' {FormEtiquetasProteticos},
  PagDentista in 'PagDentista.pas' {FormPagDentista},
  Observacoes in 'Observacoes.pas' {FormObservacoes},
  QRPagamentoDentista in 'QRPagamentoDentista.pas' {QRListaPagDentista: TQuickRep},
  RelPagamentos in 'RelPagamentos.pas' {FormRelPagamentos},
  QRPagamentoProteticoClinica in 'QRPagamentoProteticoClinica.pas' {QRListaPagProteticoClinica: TQuickRep},
  RelContratanteRepresentante in 'RelContratanteRepresentante.pas' {FormRelContratanteRepresentante},
  QRContratantePlano in 'QRContratantePlano.pas',
  QRUsuariosContratanteRepresentante in 'QRUsuariosContratanteRepresentante.pas' {QRListaUsuarioContratanteRepresentante: TQuickRep},
  RelContratantesBairro in 'RelContratantesBairro.pas' {FormRelContratantesBairro},
  QRContratoExcluidosRepresentante in 'QRContratoExcluidosRepresentante.pas' {QRListaContratosCanceladosRepresentante: TQuickRep},
  QRTaxaSuplementar in 'QRTaxaSuplementar.pas' {QRListaTaxaSuplementar: TQuickRep},
  PagProtetico in 'PagProtetico.pas' {FormPagProtetico},
  ObservacoesProteticos in 'ObservacoesProteticos.pas' {FormObservacoesProteticos},
  RelPagamentosProteticos in 'RelPagamentosProteticos.pas' {FormRelPagamentosProteticos},
  QRPagamentoProtetico in 'QRPagamentoProtetico.pas' {QRListaPagProtetico: TQuickRep},
  QRPagamentoProteticoSintetico in 'QRPagamentoProteticoSintetico.pas' {QRListaPagProteticoSintetico: TQuickRep},
  Agenda in 'Agenda.pas' {FormAgenda},
  PesquisaProtetico in 'PesquisaProtetico.pas' {FormPesquisaProteticos},
  Sobre in 'Sobre.pas' {FormSobre},
  BaixaRetorno in 'BaixaRetorno.pas' {FormBaixaRetorno},
  QRAbeCobranca in 'QRAbeCobranca.pas' {QRTitAbeCliCobranca: TQuickRep},
  QRBaiCliOrcamento in 'QRBaiCliOrcamento.pas' {QRTitBaiCliOrcamento: TQuickRep},
  RelAniversariantes in 'RelAniversariantes.pas' {FormRelAniversariantes},
  QRAniversariantes in 'QRAniversariantes.pas' {QRListaAniversariantes: TQuickRep},
  SelParamSinistralidade in 'SelParamSinistralidade.pas' {FormParamSinistralidade},
  RelSinistralidade in 'RelSinistralidade.pas' {QrSinistralidade: TQuickRep},
  PrecoGrupo in 'PrecoGrupo.pas' {FormPrecoGrupo},
  PrecoContratante in 'PrecoContratante.pas' {FormPrecoContratante},
  PrecoPlano in 'PrecoPlano.pas' {FormPrecoPlano},
  CoberturaGrupo in 'CoberturaGrupo.pas' {FormCoberturaGrupo},
  CoberturaContratante in 'CoberturaContratante.pas' {FormCoberturaContratante},
  BaixaAutomatica in 'BaixaAutomatica.pas' {FormBaixaBanespa},
  PesquisaDentista in 'PesquisaDentista.pas' {FormPesquisaDentistas},
  QRComissaoPeriodoPlano in 'QRComissaoPeriodoPlano.pas' {QRListaComissaoPeriodoPlano: TQuickRep},
  QRVendasVencimento in 'QRVendasVencimento.pas' {QRListaVendasVencimento: TQuickRep},
  QRUsuariosComissao in 'QRUsuariosComissao.pas' {QRListaUsuarioComissao: TQuickRep},
  QRComissaoPeriodo in 'QRComissaoPeriodo.pas' {QRListaComissaoPeriodo: TQuickRep},
  RelContratanteImposto in 'RelContratanteImposto.pas' {FormRelContratanteImposto},
  QRProcedimentosPagos in 'QRProcedimentosPagos.pas' {QRListaProcedimentosPagos: TQuickRep},
  QRVendasPeriodoVencEtq in 'QRVendasPeriodoVencEtq.pas' {QRListaVendasPeriodoVencEtq: TQuickRep},
  QRManutencaoCadastroSeato in 'QRManutencaoCadastroSeato.pas' {QRListaManutencaoCadastroSeato: TQuickRep},
  PesquisaCobertura in 'PesquisaCobertura.pas' {FormPesquisaCobertura},
  RelOrcamentosSip in 'RelOrcamentosSip.pas' {FormRelOrcamentosSip},
  QRVendasPeriodo in 'QRVendasPeriodo.pas' {QRListaVendasPeriodo: TQuickRep},
  QRContratoEndIncluidos in 'QRContratoEndIncluidos.pas' {QRListaContratosEndIncluidos: TQuickRep},
  QRManutencao in 'QRManutencao.pas' {QRListaManutencao: TQuickRep},
  QRFaturamentoErrosT in 'QRFaturamentoErrosT.pas' {QRListaFaturamentoErrosT: TQuickRep},
  QRFaturamentoErros in 'QRFaturamentoErros.pas' {QRListaFaturamentoErros: TQuickRep},
  QRContLigSint in 'QRContLigSint.pas' {QRListaContLigSint: TQuickRep},
  Processa in 'Processa.pas' {FormProcessa},
  RelAgenda in 'RelAgenda.pas' {FormRelAgenda},
  RelOrcamentos in 'RelOrcamentos.pas' {FormRelOrcamentos},
  QROrcamentos in 'QROrcamentos.pas' {QRListaOrcamentos: TQuickRep},
  QRRetornoBanespa in 'QRRetornoBanespa.pas' {QRListaRetornoBanespa: TQuickRep},
  CoberturaPlano in 'CoberturaPlano.pas' {FormCoberturaPlano},
  QRAcrescimo in 'QRAcrescimo.pas' {QRListaAcrescimo: TQuickRep},
  QRDiopsSIP in 'QRDiopsSIP.pas' {QRListaDiopsSip: TQuickRep},
  QRUsuariosContratante in 'QRUsuariosContratante.pas' {QRListaUsuarioContratante: TQuickRep},
  CancArqSusep in 'CancArqSusep.pas' {FormCancArqSusep},
  PesquisaContasBanco in 'PesquisaContasBanco.pas' {FormPesquisaContas_Bancos},
  QRBaiCliVen in 'QRBaiCliVen.pas' {QRTitBaiCliVencimento: TQuickRep},
  QRPagamentoDentistaRecibo in 'QRPagamentoDentistaRecibo.pas' {QRPagDentistaRecibo: TQuickRep},
  QRPagamentoDentistaClinica in 'QRPagamentoDentistaClinica.pas' {QRListaPagDentistaClinica: TQuickRep},
  QRContratoExcluidos in 'QRContratoExcluidos.pas' {QRListaContratosCancelados: TQuickRep},
  QRTitulosGerado in 'QRTitulosGerado.pas' {QrTitulosGerados: TQuickRep},
  PesquisaPlanos in 'PesquisaPlanos.pas' {FormPesquisaPlanos},
  TituloPagar in 'TituloPagar.pas' {FormTituloPagar},
  QRAbeFor in 'QRAbeFor.pas' {QRTitAbeFornecedor: TQuickRep},
  QRCanForCusto in 'QRCanForCusto.pas' {QRTitCanFornCusto: TQuickRep},
  QRAbeForCusto in 'QRAbeForCusto.pas' {QRTitAbeFornCusto: TQuickRep},
  QRBaiCli in 'QRBaiCli.pas' {QRTitBaiCliente: TQuickRep},
  RelatoReceber in 'RelatoReceber.pas' {FormRelatoriosReceber},
  QRRepresentantes in 'QRRepresentantes.pas' {QRListaRepresentantes: TQuickRep},
  QRDentistas in 'QRDentistas.pas' {QRListaDentistas: TQuickRep},
  QRProteticos in 'QRProteticos.pas' {QRListaProteticos: TQuickRep},
  QRVendedores in 'QRVendedores.pas' {QRListaVendedores: TQuickRep},
  QRReciboChequesPre in 'QRReciboChequesPre.pas' {QRRecChequesPre: TQuickRep},
  RelContratantePlano in 'RelContratantePlano.pas' {FormRelContratantePlano},
  QRReciboImpRendaDent in 'QRReciboImpRendaDent.pas' {QRReciboImpostoRendaDent: TQuickRep},
  QREtiquetasCobranca in 'QREtiquetasCobranca.pas' {QRListaEtiquetasCobranca: TQuickRep},
  OrcPagDentista in 'OrcPagDentista.pas' {FormOrcPagDentista},
  QRContratoBairro in 'QRContratoBairro.pas' {QRListaContratosBairro: TQuickRep},
  Contas_Bancos in 'Contas_Bancos.pas' {FormContas_Bancos},
  QRUsuariosContratante_2 in 'QRUsuariosContratante_2.pas' {QRListaUsuarioContratante_2: TQuickRep},
  QRManutencaoCadastro in 'QRManutencaoCadastro.pas' {QRListaManutencaoCadastro: TQuickRep},
  CarteirinhaIndividual in 'CarteirinhaIndividual.pas' {FormCarteirinhaIndividual},
  RegistrosAuxiliares in 'RegistrosAuxiliares.pas' {FormRegistrosAuxiliares},
  QRContratoIncluidos in 'QRContratoIncluidos.pas' {QRListaContratosIncluidos: TQuickRep},
  PesquisaCentroCusto in 'PesquisaCentroCusto.pas' {FormPesquisaCentroCusto},
  RelManutencao in 'RelManutencao.pas' {FormRelManutencao},
  RelOrcamentosFinalizados in 'RelOrcamentosFinalizados.pas' {FormRelOrcamentosFinalizados},
  QROrcamentosFinalizadosAtraso in 'QROrcamentosFinalizadosAtraso.pas' {QRListaOrcamentosFinalizadosAtraso: TQuickRep},
  RelContratanteInclusao in 'RelContratanteInclusao.pas' {FormRelContratanteInclusao},
  RelAtivosInativos in 'RelAtivosInativos.pas' {FormRelAtivosInativo},
  QRAbeCliVen in 'QRAbeCliVen.pas' {QRTitAbeCliVencimento: TQuickRep},
  QRVendasPeriodoVencimento in 'QRVendasPeriodoVencimento.pas' {QRListaVendasPeriodoVencimento: TQuickRep},
  QROrcamentosFinalizados in 'QROrcamentosFinalizados.pas' {QRListaOrcamentosFinalizados: TQuickRep},
  QRReciboImpRenda in 'QRReciboImpRenda.pas' {QRReciboImpostoRenda: TQuickRep},
  MenssagemItau in 'MenssagemItau.pas' {FormMenssagemItau},
  CanceladosReceber in 'CanceladosReceber.pas' {FormCanceladosReceber},
  OrcamentoDentista in 'OrcamentoDentista.pas' {QROrcamentoDentista: TQuickRep},
  QRPagamentoDentistaSintetico in 'QRPagamentoDentistaSintetico.pas' {QRListaPagDentistaSintetico: TQuickRep},
  QRPagamentoProteticoRecibo in 'QRPagamentoProteticoRecibo.pas' {QRPagProteticoRecibo: TQuickRep},
  QRContatos in 'QRContatos.pas' {QRListaContatos: TQuickRep},
  QRContLigAnalit in 'QRContLigAnalit.pas' {QRListaContLigAnalit: TQuickRep},
  EtiquetasEndereco in 'EtiquetasEndereco.pas' {QREtiquetasEnd: TQuickRep},
  QRFaturamento in 'QRFaturamento.pas' {QRListaFaturamento: TQuickRep},
  QRAbeCli in 'QRAbeCli.pas' {QRTitAbeCliente: TQuickRep},
  NetSend in 'NetSend.pas' {FmNetSend},
  QRPagamentoManutRecibo in 'QRPagamentoManutRecibo.pas' {QrPagManutencaoRecibo: TQuickRep},
  UAtualizaDB in 'UAtualizaDB.pas' {FmAtualizaDB},
  SelContratEtiquetasCobr in 'SelContratEtiquetasCobr.pas' {FmSelContrEtiqCobr},
  ArqANSRPC in 'ArqANSRPC.pas' {FmGeraArqRPCANS},
  Padrao in 'Padrao.pas' {FmPadrao},
  PrecoXUsuario in 'PrecoXUsuario.pas' {FmPrecoXusuario},
  udm in 'udm.pas' {DM: TDataModule},
  UsuarioSemMens in 'UsuarioSemMens.pas' {FMUsuarioSemMens},
  exclusaoOrcamentos in 'exclusaoOrcamentos.pas' {FmExclusaoOrcamentos},
  RelExcluidos in 'RelExcluidos.pas' {FormRelCancelamento},
  RelPadrao in 'RelPadrao.pas' {QuickReportPadrao: TQuickRep},
  RelDivergenciaVrCrianca in 'RelDivergenciaVrCrianca.pas' {QrDiverVrCrianca: TQuickRep},
  RelResumoBaixasPorBanco in 'RelResumoBaixasPorBanco.pas' {QrResumoBaixasPorBanco: TQuickRep},
  ConfANS in 'ConfANS.pas' {FmConfANS},
  enio in 'enio.pas',
  ArqSusep in 'ArqSusep.pas' {FormArqSusep},
  ArqSusepNovo in 'ArqSusepNovo.pas' {FormArqSusepNovo},
  CadCriterioOdonto in 'CadCriterioOdonto.pas' {FmCadCriterioOdonto},
  Mensagem in 'Mensagem.pas' {FmMensagem},
  RelOrcAPagar in 'RelOrcAPagar.pas' {QrOrcApagar: TQuickRep},
  ParaMOrcAPagar in 'ParaMOrcAPagar.pas' {FmParamOrcAPagar},
  Cadcidades in 'Cadcidades.pas' {FmCadCidade},
  parametro in 'parametro.pas' {FmParametro},
  LiberaOdonto in 'LiberaOdonto.pas' {FmSenhaOdonto},
  UdmAt in 'UdmAt.pas' {DmAt: TDataModule},
  GeraPerdidosANS in 'GeraPerdidosANS.pas' {FmGeraPerdidosANS},
  ConsultaTratamento in 'ConsultaTratamento.pas' {FmConsultaTrat},
  ExecutaSql in 'ExecutaSql.pas' {FmExecutaSql},
  Scripts in 'Scripts.pas' {FmScripts},
  PrecoXUsuarioDtUsu in 'PrecoXUsuarioDtUsu.pas' {FmPrecoXusuarioDtUsu},
  CadMensagens in 'CadMensagens.pas' {FmCadMensagens},
  PesqGrupoContrat in 'PesqGrupoContrat.pas' {FmPesqGrupoContrat},
  CadPacotes in 'CadPacotes.pas' {FmCadPacotes},
  RelManutAtraso in 'RelManutAtraso.pas' {QrManutAtraso: TQuickRep},
  ParamManutAtraso in 'ParamManutAtraso.pas' {FmParamManutAtraso},
  CritServicoXIdade in 'CritServicoXIdade.pas' {FmCritServicoXIdade},
  RelAbrir in 'RelAbrir.pas' {QrAbrir: TQuickRep},
  PadraoExcel in 'PadraoExcel.pas' {FmPadraoExcel},
  QtdeOrcStatus in 'QtdeOrcStatus.pas' {FmQtdeOrcamentoStatus},
  RelVendasPorUsu in 'RelVendasPorUsu.pas' {QrVendasPorUsu: TQuickRep},
  PesqPacote in 'PesqPacote.pas' {FmPesqPacote},
  DadosAdicionaisOrc in 'DadosAdicionaisOrc.pas' {FmSexHemOrcamento},
  DelimitaFace in 'DelimitaFace.pas' {FmDelimitaFace},
  ucnab in 'ucnab.pas',
  RetornoCnab240 in 'RetornoCnab240.pas' {FmRetornoCnab},
  Baca in 'Baca.pas' {FmBaca},
  PesqLocalPgCNAB in 'PesqLocalPgCNAB.pas' {FmPesqLocalPgCNAB},
  BaixaPorAtendente in 'BaixaPorAtendente.pas' {QrBaixaPAtendente: TQuickRep},
  ParamBaixaAtend in 'ParamBaixaAtend.pas' {FmParamBaixaAtend},
  PesqOperadores in 'PesqOperadores.pas' {FmPesqOperadores},
  confereFaturamento in 'confereFaturamento.pas' {FmConfFaturamento},
  ParamRelEstatFat in 'ParamRelEstatFat.pas' {FmParamRelEstatFat},
  RelEstatiFatRes in 'RelEstatiFatRes.pas' {QrEstatFatRes: TQuickRep},
  RelEstatiFatDet in 'RelEstatiFatDet.pas' {QrEstatFatDet: TQuickRep},
  CancelUsuarios in 'CancelUsuarios.pas' {QrCancelUsuarios: TQuickRep},
  PesqDentista in 'PesqDentista.pas' {FmPesqDentista},
  EndDentist in 'EndDentist.pas' {FmEndDentist},
  ReciboBaixa in 'ReciboBaixa.pas' {QrReciboBaixa: TQuickRep},
  PesqTitBaixadoSemRecibo in 'PesqTitBaixadoSemRecibo.pas' {FmTitBaixSemRecibo},
  ReimpressaoRecibo in 'ReimpressaoRecibo.pas' {FmReimpressaoRec},
  PesqTitbaixSemRecGeral in 'PesqTitbaixSemRecGeral.pas' {FmPesqTitbaixSemRecGeral},
  EfetivaPagto in 'EfetivaPagto.pas' {FmEfetivaPagto},
  CadDebCef in 'CadDebCef.pas' {FmCadDebCef},
  RelOrcClienteXDentista in 'RelOrcClienteXDentista.pas' {QrOrcClienteXDentista: TQuickRep},
  PesqLogErro in 'PesqLogErro.pas' {FmPesqLogErro},
  RelOrcViaConv in 'RelOrcViaConv.pas' {QrViaConv: TQuickRep},
  VrProcEmReal in 'VrProcEmReal.pas' {FmVrEmReal},
  DadosPromissoria in 'DadosPromissoria.pas' {FmDadosNP},
  AnsUsuXServicoPorAno in 'AnsUsuXServicoPorAno.pas' {FmANSUsuXServPorAno},
  ANS_qtdePagaServico in 'ANS_qtdePagaServico.pas' {FmAnsListaQtPaga},
  PermEspeciais in 'PermEspeciais.pas' {FmPermEspeciais},
  RelContratInadip in 'RelContratInadip.pas' {QrContratInadip: TQuickRep},
  ParamContrInad in 'ParamContrInad.pas' {FmParamContInad},
  SelTpDoc in 'SelTpDoc.pas' {FmSelTpDoc},
  relVerifMesAnterior in 'relVerifMesAnterior.pas' {FmRelVerifFatAnterior},
  RelFortesPadrao in 'RelFortesPadrao.pas' {FmFortesRepPadrao},
  RelbaixaPorAtendente in 'RelbaixaPorAtendente.pas' {FmRelBaixaPorAtendente},
  PesqProtetico in 'PesqProtetico.pas' {FmPesqProtetico},
  SimulacaoPgtit in 'SimulacaoPgtit.pas' {FmSimulPgTit},
  RelFrConfCartoes in 'RelFrConfCartoes.pas' {FmRelFrConfCartoes},
  ParamRelConfCart in 'ParamRelConfCart.pas' {FmParamRelConfCart},
  BoletoBancoob in 'BoletoBancoob.pas' {FmBoletoBancoob},
  ErroAtualizacao in 'ErroAtualizacao.pas' {FmErroAtualizacao},
  wscep in 'wscep.pas',
  BaixaCnab400 in 'BaixaCnab400.pas' {FmBaixaCnab400},
  ConsultaEventoOdonto in 'ConsultaEventoOdonto.pas' {FmConsEventoOdonto},
  ControleFaturamento in 'ControleFaturamento.pas' {FmFaturamento},
  eventoFat in 'eventoFat.pas' {FmEventosFat},
  ParamDebAut in 'ParamDebAut.pas' {FmParamDebAuto},
  DetalheFat in 'DetalheFat.pas' {FmDetalheFat},
  RelFrVendasPeridTitular in 'RelFrVendasPeridTitular.pas' {FrVendPeridTitular},
  RelContrVendasEmp in 'RelContrVendasEmp.pas' {FmFrContrVendasEmp},
  ParamRelContVidasEmp in 'ParamRelContVidasEmp.pas' {FmParamRelContVidasEmp},
  GraficoIngressosXExclusoes in 'GraficoIngressosXExclusoes.pas' {FmGraficIncXExc},
  relEtiquetas in 'relEtiquetas.pas' {FmFrEtiquetas},
  RelOrcExcluidos in 'RelOrcExcluidos.pas' {FmFrOrcExcluidos},
  ParamDatas in 'ParamDatas.pas' {FmParamData},
  ParamDtRelOrcExc in 'ParamDtRelOrcExc.pas' {FmParamDtRelOrcExc},
  CadMenu in 'CadMenu.pas' {FmCadMenu},
  CadGrupoFunc in 'CadGrupoFunc.pas' {FmCadGrupoFunc},
  PermGrupo in 'PermGrupo.pas' {FmPermGrupo},
  PermFunc in 'PermFunc.pas' {fmPermFunc},
  RelFrCustoDentista in 'RelFrCustoDentista.pas' {FmFrCustoDentista},
  ParamRelCustoDent in 'ParamRelCustoDent.pas' {FmParamRelCustoDent},
  RelFortesPadraoGroup in 'RelFortesPadraoGroup.pas' {FmFortesPadraoGroup},
  RelFrCustoDentistaDetail in 'RelFrCustoDentistaDetail.pas' {FmFrRelCustoDentDetail},
  RelFrCustoDentistaDetailServ in 'RelFrCustoDentistaDetailServ.pas' {FmFrRelFrCustoDentistaDetailServ},
  RelFrFinanCliente in 'RelFrFinanCliente.pas' {FmRelFrFinanCliente},
  RelFichaFinan in 'RelFichaFinan.pas' {FmRelFichaFinan},
  CadTabPagto in 'CadTabPagto.pas' {FmCadTabPagto},
  TabPagtoVrServico in 'TabPagtoVrServico.pas' {FmTabPagtoVrServico},
  CopiarTab in 'CopiarTab.pas' {FmCopiarTab},
  TabPagtoXProtetico in 'TabPagtoXProtetico.pas' {FmTabPagtoProtetico},
  TabPagtoXDentista in 'TabPagtoXDentista.pas' {FmTabPagtoDentista},
  RelAniverInclusaoDentista in 'RelAniverInclusaoDentista.pas' {fmfrNiverInclusaoDentista},
  paramNiverIncDent in 'paramNiverIncDent.pas' {FmParamNiverIncDent},
  listaServicosCoincidentes in 'listaServicosCoincidentes.pas' {FmServCoincidentes},
  DadosBancarios in 'DadosBancarios.pas' {FmDadosBancario},
  Associa_cco in 'Associa_cco.pas' {FmAssociaCCO},
  ArqErroSib in 'ArqErroSib.pas' {FmCargaErroSib},
  RelFrErroSib in 'RelFrErroSib.pas' {FrRelErroSib},
  EnvDentistaGrafica in 'EnvDentistaGrafica.pas' {FmEnvDentistaGrafica},
  RelEnvDentistaGrafica in 'RelEnvDentistaGrafica.pas' {FmFrEnvDentistaGrafica},
  RelAniverInclusaoProtetico in 'RelAniverInclusaoProtetico.pas' {fmfrNiverInclusaoProtetico},
  SelecionaNovoTitular in 'SelecionaNovoTitular.pas' {FmSelecionaNovoTitular},
  PesqOrcamentosExc in 'PesqOrcamentosExc.pas' {FmPesqOrcamentosExc},
  RelfrContratSolicReciboIR in 'RelfrContratSolicReciboIR.pas' {FmfrContratSolicReciboIR},
  relfrDmed in 'relfrDmed.pas' {FmFrRelDmed},
  relViaProteticoGraf in 'relViaProteticoGraf.pas' {fmFrViaProteticoGraf},
  FrViaOrtodontGraf in 'FrViaOrtodontGraf.pas' {fmFrViaOrtodontGraf},
  UAtualizaDBAux in 'UAtualizaDBAux.pas',
  PesqLogContrat in 'PesqLogContrat.pas' {FmPesqLogContratante},
  PesqlogAltUsu in 'PesqlogAltUsu.pas' {FmPesqLogAltUsu},
  CadServicosImcompativeisOdonto in 'CadServicosImcompativeisOdonto.pas' {FmCadServIncompativeisOdonto},
  paramRelPrevMens in 'paramRelPrevMens.pas' {fmParamPrevMens},
  RelFrResumoBaixaPorData in 'RelFrResumoBaixaPorData.pas' {FmFrRelResumoBaixaPorData},
  RelFrParcOrcDesFolha in 'RelFrParcOrcDesFolha.pas' {FmFrParcOrcDesFolha},
  seltpRelEmrpesa in 'seltpRelEmrpesa.pas' {fmSelRelEmpresa},
  relRetiradaCarteira in 'relRetiradaCarteira.pas' {FmFrRetiradaCarteira},
  GraficoRecebMensXOrcamento in 'GraficoRecebMensXOrcamento.pas' {fmGrafMensXOrcamento},
  SelTipoRel in 'SelTipoRel.pas' {fmTipoRel},
  dmed in 'dmed.pas' {FmDMED},
  manutencaoDMED in 'manutencaoDMED.pas' {FmManutencaoDMED},
  CadBloqueioContrat in 'CadBloqueioContrat.pas' {FmCadBloqueioContrat},
  relContratRestricaoTitPago in 'relContratRestricaoTitPago.pas' {FmFrrContratRestricaoTitPago},
  ParamRelTitPgContratRestricao in 'ParamRelTitPgContratRestricao.pas' {FmParamRelTitPgContratRestricao},
  avisoContratante in 'avisoContratante.pas' {FmAvisoContratante},
  FmParamVrServPorPlano in 'FmParamVrServPorPlano.pas' {FmParamServicoPorPLano},
  RelFrServicoPorPlano in 'RelFrServicoPorPlano.pas' {FrRelServicoPorPlano},
  RelFrUsuariosContratante in 'RelFrUsuariosContratante.pas' {FrListaUsuarioContratante},
  CadRegiao in 'CadRegiao.pas' {FmCadRegiao},
  RelCarteirinha in 'RelCarteirinha.pas' {fmFrRelCarteirinha},
  emissaoCarteirinha in 'emissaoCarteirinha.pas' {FmEmissaoCarteirinha},
  FrRelComprovatenEntregaCart in 'FrRelComprovatenEntregaCart.pas' {fMFrRelComprovatenEntregaCart},
  RelManutencaoClinica in 'RelManutencaoClinica.pas' {QrManutencaoClinica: TQuickRep},
  RelManutencaoClinicaAu in 'RelManutencaoClinicaAu.pas' {QrManutencaoClinicaAU: TQuickRep},
  SelRPS in 'SelRPS.pas' {FmSelRPS},
  fmLogReceber in 'fmLogReceber.pas' {FmLogAltReceber},
  USms in 'USms.pas' {FmEnviaSMS},
  Prjsms in 'Prjsms.pas',
  cadMensagemSMS in 'cadMensagemSMS.pas' {FmCadMensagemSMS},
  paramEtiq in 'paramEtiq.pas' {FmParamEtiq};

{$R *.RES}

begin
  Application.Initialize;
  Application.Title := 'Controle Administrativo';
  Application.CreateForm(TFormFundo, FormFundo);
  Application.CreateForm(TFormSenha, FormSenha);
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TFmCadMensagemSMS, FmCadMensagemSMS);
  {  if DebugHook <> 0 then
  begin
     FormSenha.FormShow(FormSenha);
     FormSenha.EditUsuario.text := 'ENIO';
     FormSenha.EditSenha.text := '183729';
     FormSenha.BitBtnOkClick(FormSenha);
  end
  else}
  FormSenha.ShowModal;
  Application.CreateForm(TFormSeletor, FormSeletor);
  FormSeletor.SetFocus;
  Application.Run;
 end.
