--use mt select * from contrat_dmed
--select sum(valor), tipo from contrat_dmed group by tipo
--use multiodonto
--select 'insert into contrat_dmed values (2010,' + cast(cd_contratante as varchar(20)) + ',''' + tipo + ''',' + str(valor,12,2) + ')' from contrat_dmed
--use
--select sum(valor_pago), tipo from #dmed where lg_pode_alterar = 'N' group by tipo
--select tipo, sum(valor) from R group by tipo
-- delete CONTRAT_DMED
--use st
/*
ESSE SCRIPT AJUSTA O DMED COM RELAÇÃO AO VALOR DE ORÇAMENTO QUE DEVE IR, VERIFICA OS CONTRATANTES QUE DEVEM IR OBRIGATORIAMENTE
 1)CONTRAT. QUE SOLICITARAM IR EM 2010 E 2009
 2)CONTRAT. QUE ENTRARAM EM 2010 PARA FRENTE.

 A TABELA VR_DMED CONTEM O VALOR QUE DEVE IR DE ORÇAMENTO E MENSALIDADE(ESSE SCRIPT SO TRATA O ORÇAMENTO POIS EM 2010 O VALOR DE MENS EH MENOR QUE O VALOR APURADO)
 SE NECESSÁRIO NOS PROXIMOS ANOS PRECISA FAZER A TRATATIVA PARA MENSALIDADES.

 A TABELA CONTRAT_DMED SÃO OS CONTRATANTES QUE VÃO SER ENVIADOS AO DMED. 
 VERIFICAR OS ANOS FIXO ABAIXO 2009,2010 PARA OUTROS ANOS DEVE SER ALTERADO
*/

DECLARE

@DTINI CHAR(10),
@DTFIM CHAR(10),
@EMPRESA CHAR(2)

SET @EMPRESA = 'ST'

--AS
-- DROP TABLE #T	DROP TABLE #DMED DROP TABLE #DMED_CONTRAT DROP TABLE #DMED_CONTRAT1 DROP TABLE #DMED_CONTRAT_MENS DROP TABLE #DMED_CONTRAT1_MENS
SET @DTINI = '01/01/2012'
SET @DTFIM = '31/12/2012'

SET DATEFORMAT DMY
--INSERT INTO #DMED
--SELECT SUM(VALOR_PAGO) FROM #DMED WHERE TIPO = 'M'
 

--SELECT Valor_Pago,* FROM Receber WHERE CODIGO_CONTRATANTE = 19993 AND Valor_Pago > 0 AND YEAR(DATA_PAGAMENTO) = 2012

SELECT  

    C.NOME AS NM_CONTRATANTE,
	R.TIPO_DOCUMENTO,
    T.DESCRICAO AS DSTPDOCUMENTO,
	R.VALOR_PAGO, 
	R.DATA_PAGAMENTO ,
	R.CODIGO_CONTRATANTE,
	R.CODIGO_USUARIO, 
	ISNULL(R.DTINCLUSAO,DATA_EMISSAO) DTINCLUSAO,
    R.ORCAMENTO,    
    C.CODIGO,
    C.CODIGO AS CD_CONTRATANTE,
    'S' LG_PODE_ALTERAR,
    'N' FLEGAR,
    CAST(NULL AS BIT) lg_ir,
    CAST(NULL AS DATETIME) DATA_INCLUSAO,
    C.INCLUSAO AS DT_INCLUSAO_CONTRAT,
    'M' TIPO,
    cast('' as varchar(50)) MOTIVO
    
    

INTO #DMED

FROM 
	RECEBER R, 
	TIPODOCUMENTO T,
    CONTRATANTE C,
    PLANO P

WHERE 
	     T.CODIGO = R.TIPO_DOCUMENTO 
        AND C.CODIGO  = R.CODIGO_CONTRATANTE
        AND P.CODIGO  = C.PLANO
	AND DATA_PAGAMENTO BETWEEN @DTINI AND @DTFIM
	AND VALOR_PAGO > 0 -- SEGUNDO GABI SOMENTE LISTA QUEM PAGOU NO MES..
	AND C.Empresa = 0
    --AND P.FIS_JUR = 'Física' -- SEGUNDO GABI SOMENTE PESSOA FÍSICA..
    and T.CODIGO IN(select CODIGO from TipoDocumento where Classificacao = 'Mensalidade')
--    and t.codigo in(1,4,9,10,11,14,15,16,18,21,23,26)

INSERT INTO #DMED

SELECT  
    U.NOME AS NM_CONTRATANTE,
    R.TIPO_DOCUMENTO,
    T.DESCRICAO AS DSTPDOCUMENTO,
	R.VALOR_PAGO, 
	R.DATA_PAGAMENTO ,
	R.CODIGO_CONTRATANTE,
	R.CODIGO_USUARIO, 
	ISNULL(R.DTINCLUSAO,DATA_EMISSAO) DTINCLUSAO,
    R.ORCAMENTO,
    U.CODIGO_COMPLETO,
    U.CODIGO AS CD_CONTRATANTE,
    'S' LG_PODE_ALTERAR,
    'N' FLEGAR,
    O.lg_ir,
    U.DATA_INCLUSAO,
    C.INCLUSAO AS DT_INCLUSAO_CONTRAT,
    'O' TIPO,
    '' motivo

 
FROM 
	RECEBER R

INNER JOIN	TIPODOCUMENTO T 
ON
   T.CODIGO = R.TIPO_DOCUMENTO 

INNER JOIN USUARIO U 
ON
   U.CODIGO_COMPLETO = R.CODIGO_USUARIO

INNER JOIN CONTRATANTE C
ON
    C.CODIGO  = U.CODIGO

INNER JOIN ORCAMENTO O
ON
  O.NUMERO = R.ORCAMENTO --TB ORCAMENTO
  

WHERE 
	        
	    DATA_PAGAMENTO BETWEEN @DTINI AND @DTFIM
	AND VALOR_PAGO > 0 -- SEGUNDO GABI SOMENTE LISTA QUEM PAGOU NO MES..
    --AND FIS_JUR = 'Física' -- SEGUNDO GABI ORÇAMENTOS MANUT É O BENEF. QUE PAGA, INTÃO NÃO VERIFICA SE É PJ OU PF
   AND T.CODIGO IN(select CODIGO from TipoDocumento where Classificacao <> 'Mensalidade')    -- orc. e manut)    
   
   /* AND T.CODIGO IN(2, -- ORC
					3, -- ORC IMPL
					5, -- MANUT
					6, -- EMERG
				   20) -- MANUT IMPL
*/
--select SUM(valor_pago) from #DMED
update #dmed set lg_ir = 0 where lg_ir is null
--select cd_contratante,sum(valor_pago),LG_IR from #dmed  where tipo = 'O' group by LG_IR, cd_contratante order by cd_contratante select * from #dmed where cd_contratante = 47

--UPDATE #DMED SET LG_PODE_ALTERAR = 'S'
if @EMPRESA in('MT','ST')
BEGIN
   
   UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'CONTRATANTE NOVO' WHERE YEAR(DT_INCLUSAO_CONTRAT) >= 2012

   UPDATE #DMED SET LG_PODE_ALTERAR = 'N',MOTIVO = 'ENVIAR TODAS MENSALIDADES' WHERE TIPO = 'M'
   
END
--UPDATE #DMED SET LG_PODE_ALTERAR = 'S'
-- NÃO MEXE NOS CONTRATANTES QUE ENTRARAM EM 2010, PORQUE NÃO OS CONHECEMOS E NAO SABEMOS SE PEDIRÃO OU NÃO IR.

--select * from RECIBOIR_CONTRATANTE where cd_contratante = 
-- TODO MUNDO QUE DISSE QUE VAI PEDIR 
-- em 2011 nao usou o recurso abaixo
if @empresa = 'ST'
begin
   SELECT DISTINCT CD_CONTRATANTE INTO #T FROM #DMED WHERE LG_IR = 1
   --select count(*) from #dmed where lg_ir = 0 select * from #T

   UPDATE #DMED SET LG_PODE_ALTERAR = 'N',MOTIVO = 'SEATO - INFORMOU NO ORÇC QUE VAI USAR PARA IR NOVO' FROM #T WHERE #DMED.CD_CONTRATANTE = #T.CD_CONTRATANTE and tipo = 'O' and YEAR(DT_INCLUSAO_CONTRAT) >= 2012
   UPDATE #DMED SET LG_PODE_ALTERAR = 'N',MOTIVO = 'SEATO - INFORMOU NO ORÇC QUE VAI USAR PARA IR ANTI' FROM #T WHERE #DMED.CD_CONTRATANTE = #T.CD_CONTRATANTE and tipo = 'O' and YEAR(DT_INCLUSAO_CONTRAT) < 2012
end


UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'SOLICITOU RECIBO DE IR' FROM RECIBOIR_CONTRATANTE R WHERE R.CD_CONTRATANTE = #DMED.CD_CONTRATANTE AND R.ANO IN(2010,2011,2012)



--select cd_contratante,lg_ir,LG_PODE_ALTERAR,* from #dmed order by cd_contratante

--begin tran UPDATE #DMED SET LG_PODE_ALTERAR = 'N', MOTIVO = 'INFORMOU NO ORC QUE VAI USAR PARA IR' WHERE LG_IR = 1 and lg_pode_alterar = 'S'
rollback
COMMIT

-- NÃO MEXE NOS CONTRATANTES QUE PEDIRAM DECLARAÇÃO DE IR NOS ANOS DE 2009 E 2010					




--- lista por tipo de documento para analise
SELECT MOTIVO,DSTPDOCUMENTO, replace(str(SUM(VALOR_PAGO),10,2),'.',',') vr_pago FROM #DMED WHERE LG_PODE_ALTERAR = 'N' group by DSTPDOCUMENTO,motivo order by 1,2



-- LISTA AGRUPADO POR MENSALIDADE/ORCAMENTO
SELECT TIPO, replace(str(SUM(VALOR_PAGO),10,2),'.',',') vr_pago FROM #DMED  GROUP BY TIPO
--SELECT TIPO, replace(str(SUM(VALOR_PAGO),10,2),'.',',')  vr_pago FROM #DMED WHERE LG_PODE_ALTERAR = 'N'  GROUP BY TIPO



--SELECT TOP 10 * FROM #DMED SELECT DISTINCT DSTPDOCUMENTO FROM #DMED


SELECT CODIGO_CONTRATANTE,NM_CONTRATANTE,DSTPDOCUMENTO, SUM(Valor_Pago) AS VALOR_PAGO, MOTIVO FROM #DMED WHERE LG_PODE_ALTERAR = 'S' 
GROUP BY CODIGO_CONTRATANTE,NM_CONTRATANTE,DSTPDOCUMENTO,  MOTIVO ORDER BY 4 DESC
--select * into contrat_dmed_original from contrat_dmed
--SELECT COUNT(*) FROM #DMED WHERE LG_PODE_ALTERAR = 'N'
--SELECT DISTINCT LG_PODE_ALTERAR FROM #DMED WHERE CD_CONTRATANTE = 5636

--DROP TABLE #DMED_CONTRAT1
--SELECT SUM(VALOR_PAGO) VALOR_PAGO FROM #DMED WHERE LG_PODE_ALTERAR = 'S' GROUP BY CD_CONTRATANTE
-- EM 2012/2011 A GABI DISSE QUE A REGRA EH TIRAR DOS CONTRATANTES QUE ENTRARAM EM 2011

if @EMPRESA = 'MT'
begin
   SELECT CD_CONTRATANTE,SUM(VALOR_PAGO) VALOR_PAGO INTO #DMED_CONTRAT FROM #DMED WHERE LG_PODE_ALTERAR = 'S' AND TIPO = 'O' AND DTINCLUSAO >= '01/01/2011'
   -- em 2012 nao mandar o contratante 3315 pq ja declarou o IR e nao listou multiodonto.
   and CD_CONTRATANTE <> 3315  GROUP BY CD_CONTRATANTE order by valor_pago desc

   SELECT IDENTITY(INT,1,1) INDICE, * INTO #DMED_CONTRAT1 FROM #DMED_CONTRAT ORDER BY VALOR_PAGO desc
--   SELECT * FROM #DMED_CONTRAT1
end
else
begin
   SELECT CD_CONTRATANTE,SUM(VALOR_PAGO) VALOR_PAGO INTO #DMED_CONTRAT FROM #DMED WHERE LG_PODE_ALTERAR = 'S' AND TIPO = 'O' AND DTINCLUSAO >= '01/01/2011'  GROUP BY CD_CONTRATANTE order by valor_pago desc

   SELECT IDENTITY(INT,1,1) INDICE, * INTO #DMED_CONTRAT1 FROM #DMED_CONTRAT ORDER BY VALOR_PAGO desc

end

-- DROP TABLE #DMED_CONTRAT_MENS DROP TABLE #DMED_CONTRAT1_MENS
SELECT CD_CONTRATANTE,SUM(VALOR_PAGO) VALOR_PAGO INTO #DMED_CONTRAT_MENS FROM #DMED WHERE LG_PODE_ALTERAR = 'S' AND TIPO = 'M' GROUP BY CD_CONTRATANTE order by valor_pago desc
SELECT IDENTITY(INT,1,1) INDICE, * INTO #DMED_CONTRAT1_MENS FROM #DMED_CONTRAT_MENS ORDER BY VALOR_PAGO desc
--SELECT SUM(VALOR_PAGO) VALOR_PAGO FROM #DMED WHERE LG_PODE_ALTERAR = 'S' AND TIPO = 'M'
--select sum(valor_pago) from #DMED_CONTRAT1

DECLARE @MAX INT
DECLARE @INDICE INT
DECLARE @VALOR MONEY
DECLARE @ANO INT
declare @empresa char(2) 
set @empresa = 'ST'
--SELECT  cd_contratante,nm_contratante, str(SUM(VALOR_PAGO),12,2)  valor_pago FROM #DMED B WHERE  LG_PODE_ALTERAR = 'N'  group by cd_contratante,nm_contratante order by 1
SET @ANO = 2011
--DELETE CONTRAT_DMED
-- INSERI NA TABELA CONTRAT_DMED OS CONTRATANTES QUE NAO PODEM SER MEXIDOS
INSERT INTO CONTRAT_DMED SELECT @ANO,CD_CONTRATANTE,'O', SUM(VALOR_PAGO),'ORCAMENTOS QUE NAO PODE ALTERAR(IR)' FROM #DMED B WHERE  LG_PODE_ALTERAR = 'N' 
AND B.TIPO = 'O' AND NOT EXISTS(SELECT * FROM CONTRAT_DMED A WHERE A.ANO = @ANO AND A.CD_CONTRATANTE = B.CD_CONTRATANTE AND A.TIPO = 'O')
GROUP BY CD_CONTRATANTE
--delete contrat_dmed where ano = 2011

-- INSERI COMO MENSALIDADE
/*
   INSERT INTO CONTRAT_DMED SELECT 2010,CD_CONTRATANTE,'M', SUM(VALOR_PAGO) FROM #DMED B WHERE  LG_PODE_ALTERAR = 'N' AND B.TIPO = 'M'
   AND NOT EXISTS(SELECT * FROM CONTRAT_DMED A WHERE A.ANO = 2010 AND A.CD_CONTRATANTE = B.CD_CONTRATANTE AND A.TIPO = 'M')
   GROUP BY CD_CONTRATANTE
*/  
--SELECT * FROM CONTRAT_DMED WHERE ANO = 2011
--ALTER TABLE CONTRAT_DMED ADD OBS VARCHAR(50)
if @empresa in('ST','MT')
begin
   --DECLARE @ANO INT SET @ANO = 2011
   INSERT INTO CONTRAT_DMED SELECT @ANO,CD_CONTRATANTE,'M', SUM(VALOR_PAGO),'MENSALIDADES' FROM #DMED B WHERE  LG_PODE_ALTERAR = 'N' AND B.TIPO = 'M'
   AND NOT EXISTS(SELECT * FROM CONTRAT_DMED A WHERE A.ANO = @ANO AND A.CD_CONTRATANTE = B.CD_CONTRATANTE AND A.TIPO = 'M')
   GROUP BY CD_CONTRATANTE
end

--SEATO 2011 --LOUCURA NA MINHA KBÇA
/*
da Seato vai
 
Enio, vamos la então...
Mensalidades todas = 205.897,68
Orçamento (48.471,46) + manut (23.714,25) pediu recibo IR = 72.185,71
Orçamento (42.934,26) + manut (7.569,61) repondeu sim pegunta orç contra. novo = 50.503,87
Total = 328.587,26
 
Para o total a enviar 335.062,61 falta 6.475,35
*/
--SELECT MOTIVO,DSTPDOCUMENTO, replace(str(SUM(VALOR_PAGO),10,2),'.',',') vr_pago FROM #DMED WHERE LG_PODE_ALTERAR = 'N' group by DSTPDOCUMENTO,motivo order by 1,2
   DECLARE @ANO INT SET @ANO = 2012
   INSERT INTO CONTRAT_DMED SELECT @ANO,CD_CONTRATANTE,'O', SUM(VALOR_PAGO),'ORCAMENTOS E MANUT DE QUEM SOLICITOU REC IR ' FROM #DMED B WHERE  LG_PODE_ALTERAR = 'N' AND B.TIPO = 'O'
   and b.MOTIVO = 'SOLICITOU RECIBO DE IR' and DSTPDOCUMENTO IN('ORCAMENTO','MANUTENCAO')
   AND NOT EXISTS(SELECT * FROM CONTRAT_DMED A WHERE A.ANO = @ANO AND A.CD_CONTRATANTE = B.CD_CONTRATANTE AND A.TIPO = 'O')
   GROUP BY CD_CONTRATANTE   
   
   DECLARE @ANO INT SET @ANO = 2012
   INSERT INTO CONTRAT_DMED SELECT @ANO,CD_CONTRATANTE,'O', SUM(VALOR_PAGO),'INDICOU USAR ORÇ P/ IR CONTRAT NOVOS' FROM #DMED B WHERE  LG_PODE_ALTERAR = 'N' AND B.TIPO = 'O'
   
   and b.MOTIVO = 'SEATO - INFORMOU NO ORÇC QUE VAI USAR PARA IR NOVO' and DSTPDOCUMENTO IN('ORCAMENTO','MANUTENCAO')
   AND NOT EXISTS(SELECT * FROM CONTRAT_DMED A WHERE A.ANO = @ANO AND A.CD_CONTRATANTE = B.CD_CONTRATANTE AND A.TIPO = 'O')
   GROUP BY CD_CONTRATANTE
   
   INSERT INTO CONTRAT_DMED SELECT 2011, CD_CONTRATANTE, 'O',valor_pago,'ORCAMENTOS ESCOLHIDO PARA FECHAR VALOR' FROM #DMED_CONTRAT1 WHERE INDICE in(1,2)

   

SELECT OBS, SUM(VALOR) VR  FROM CONTRAT_DMED WHERE ANO = 2011 GROUP BY OBS
--SELECT SUM(VALOR) VR  FROM CONTRAT_DMED WHERE ANO = 2011
--SELECT * FROM CONTRAT_DMED WHERE CD_CONTRATANTE = 5636
--SELECT * FROM #DMED_CONTRAT WHERE CD_CONTRATANTE = 5636
--DELETE CONTRAT_DMED WHERE ANO = 2011
--DELETE CONTRAT_DMED WHERE TIPO <> 'm'
SET @INDICE = 1
SET @MAX = (SELECT MAX(INDICE) FROM #DMED_CONTRAT1)
SET @VALOR = (SELECT SUM(VALOR) FROM CONTRAT_DMED WHERE ANO = @ANO AND TIPO = 'O')
DECLARE @VRORCAMENTO MONEY
--SELECT * FROM VR_DMED
--MT INSERT INTO VR_DMED VALUES(2011,'O',125511.68) INSERT INTO VR_DMED VALUES(2011,'M',690710.80)
--ST INSERT INTO VR_DMED VALUES(2011,'O',128992.22) INSERT INTO VR_DMED VALUES(2011,'M', 205897.68)
--select * FROM VR_DMED
SET @VRORCAMENTO = (SELECT VALOR FROM VR_DMED WHERE TIPO = 'O' AND ANO = @ANO)
-- o valor vai ficar bem próximo , mas não irá bater, se for necessário que bata precisa alterar um valor qualquer 
--SELECT CD_CONTRATANTE, COUNT(*) FROM #DMED_CONTRAT1 GROUP BY CD_CONTRATANTE HAVING COUNT(*) > 1
--select sum(valor) from CONTRAT_DMED WHERE TIPO = 'M'
declare @vrAux money -- SERVE PARA EVITAR QUE O VALOR ULTRAPASSE AO VALOR @VRORCAMENTO

--SELECT TIPO, SUM(VALOR) VALOR FROM CONTRAT_DMED WHERE ANO = 2011 GROUP BY TIPO

--SELECT * FROM #DMED_CONTRAT1 
WHILE @INDICE <= @MAX
BEGIN
   
   IF @VALOR >= @VRORCAMENTO
      SET @INDICE = @MAX + 1
   ELSE
   BEGIN
      IF (@VALOR +  (SELECT VALOR_PAGO FROM #DMED_CONTRAT1 WHERE INDICE = @INDICE)) > @VRORCAMENTO 
      BEGIN
        
        
        SET @vrAux =   @VRORCAMENTO - @VALOR
        --SELECT @vrAux,@VALOR, @VRORCAMENTO

        --SELECT 'IF'
      END
      ELSE
      BEGIN
        SET @vrAux =  (SELECT VALOR_PAGO FROM #DMED_CONTRAT1 WHERE INDICE = @INDICE)
        --SELECT 'ELSE'
      END

--      SELECT VALOR_PAGO FROM #DMED_CONTRAT1 WHERE INDICE = @INDICE

      --SELECT @VALOR, @VRAUX
      SET @VALOR = @VALOR + @vrAux
      
      INSERT INTO CONTRAT_DMED SELECT @ANO, CD_CONTRATANTE, 'O',@vrAux,'ORCAMENTOS ESCOLHIDO MAIOR VR CONTRA NOVO' FROM #DMED_CONTRAT1 WHERE INDICE = @INDICE
      SET @INDICE = @INDICE + 1
  END
     
   
END

-- TROCA O ULTIMO CONTRATANTE POR ESSE PORQUE O VALOR TÁ BEM PROXIMO (2011)
--UPDATE CONTRAT_DMED SET CD_CONTRATANTE = 13601, VALOR = 2616.30 WHERE ANO = 2011 AND CD_CONTRATANTE = 22014 AND TIPO = 'O'

--select SUM(valor) from contrat_dmed where ano = 2011
-- select c.nome, a.* from contrat_dmed a, contratante c where c.codigo = a.cd_contratante and ano = 2011 and obs = 'ORCAMENTOS ESCOLHIDO MAIOR VR CONTRA NOVO'
--SELECT * FROM VR_DMED
--SELECT a.*, nome,fone1,fone2,fax FROM #DMED_CONTRAT1 a, contratante c where a.cd_contratante = c.codigo ORDER BY 3 DESC
SELECT @VALOR

--SELECT * FROM CONTRAT_DMED WHERE ANO = 2011 AND CD_CONTRATANTE = 20207
-- MENSALIDADES..
if @empresa IN('ST','MT') then -- somente para seato mt manda tudo
begin
DECLARE @MAX INT
DECLARE @INDICE INT
DECLARE @VALOR MONEY
DECLARE @ANO INT

SET @ANO = 2010

SET @INDICE = 1
SET @MAX = (SELECT MAX(INDICE) FROM #DMED_CONTRAT1_MENS)
SET @VALOR = (SELECT SUM(VALOR) FROM CONTRAT_DMED WHERE TIPO = 'M')
DECLARE @VRMENSALIDADE MONEY
declare @vrAux money
SET @VRMENSALIDADE = (SELECT VALOR FROM VR_DMED WHERE TIPO = 'M')
-- o valor vai ficar bem próximo , mas não irá bater, se for necessário que bata precisa alterar um valor qualquer 
set @vrAux = 0
-- SELECT SUM(VALOR_PAGO) FROM #DMED_CONTRAT1_MENS 
WHILE @INDICE <= @MAX
BEGIN
   IF @VALOR >= @VRMENSALIDADE
      SET @INDICE = @MAX + 1
   ELSE
   BEGIN
      IF (@VALOR +  (SELECT VALOR_PAGO FROM #DMED_CONTRAT1_MENS WHERE INDICE = @INDICE)) > @VRMENSALIDADE

         SET @vrAux = @VRMENSALIDADE - @VALOR

      ELSE
         SET @vrAux =  (SELECT VALOR_PAGO FROM #DMED_CONTRAT1_MENS WHERE INDICE = @INDICE)

      SET @VALOR = @VALOR + @vrAux
      SELECT @VALOR VALOR, @VRAUX AUX, @VRMENSALIDADE MENS
      INSERT INTO CONTRAT_DMED SELECT @ANO, CD_CONTRATANTE, 'M',@vrAux FROM #DMED_CONTRAT1_MENS WHERE INDICE = @INDICE
      SET @vrAux = 0
      SET @INDICE = @INDICE + 1
--   DELETE CONTRAT_DMED WHERE TIPO = 'M'
   END
   
END
--SELECT * FROM CONTRAT_DMED where tipo = 'M' SELECT sum(valor) FROM CONTRAT_DMED where tipo = 'M'
SELECT @VALOR
end
--SELECT * FROM CONTRAT_DMED WHERE VALOR < 0
--SELECT SUM(VALOR), tipo FROM CONTRAT_DMED group by tipo
--SELECT SUM(VALOR) FROM DELETE CONTRAT_DMED
/*
CREATE TABLE CONTRAT_DMED
(ANO INT,
 CD_CONTRATANTE INT,
 TIPO CHAR(1), -- ORCAMENTO MENSALIDADE
 VALOR MONEY,
 CONSTRAINT PK_CONTRAT_DMED PRIMARY KEY (ANO,CD_CONTRATANTE,TIPO)
 )
select * from vr_dmed
CREATE TABLE VR_DMED (ANO INT, TIPO CHAR(1), VALOR MONEY CONSTRAINT PK_VR_DMED PRIMARY KEY(ANO,TIPO))
 INSERT INTO VR_DMED VALUES(2010,'O',265941.13)
 INSERT INTO VR_DMED VALUES(2010,'M',1066920.99)

INSERT INTO VR_DMED VALUES(2010,'O',142651.89)
 INSERT INTO VR_DMED VALUES(2010,'M',176217.39)
-- SELECT * FROM VR_DMED 
A mensalidade de pessoas físicas é R$ 176217.39.
E os tratamento de pessoas físicas é R$ 142651.89.
*/
SELECT SUM(VALOR_PAGO) FROM #DMED_CONTRAT --WHERE LG_PODE_ALTERAR = 'N'


--select * from contrat_dmed where cd_contratante in

/*select * from contrat_dmed where cd_contratante in
-- gabi fez analise e pediu para tirar esses contrat do dmed serrana, dei um delete na tabela abaixo
