--coloca na tabela #nomes os nomes de envio ao sib para achar um caracater que nao esta na tabela c
declare @i int
declare @j int

set @i = 1
set @j = (select max(indice) from #nomes)

declare @nome varchar(100)
declare @max int
declare @k int

while @i <= @j
begin
   select @nome = nome from #nomes where indice = @i
   set @max = len(@nome)
   set @k = 1
   while @k <= @max   
   begin
      if not exists(select * from c where c = substring(@nome,@k,1))
         select @nome as nome, substring(@nome,@k,1) as caracter
      set @k = @k + 1
   end
   set @i = @i + 1
end

--create table #nome (nome varchar(100))
--select identity(int,1,1) indice, nome into #nomes from #nome
/*
insert into #nome values ('ADAUANA CARDOSO MESSIAS ')
insert into #nome values ('ADAYLTON APARECIDO DOS SANTOS')
insert into #nome values ('ADEILSON FERREIRA DA SILVA')
insert into #nome values ('ADEILSON FERREIRA RODRIGUES DA SILVA')
insert into #nome values ('ADEMIR CUNHA DE OLIVEIRA')
insert into #nome values ('ADMILSON SANTOS DA SILVA')
insert into #nome values ('ADRIANA ANDRESSA SOARES')
insert into #nome values ('ADRIANA APARECIDA ROBERTO')
insert into #nome values ('ADRIANA BALBINO VOLPATO')
insert into #nome values ('ADRIANA BENVEGNU BACHEGA')
insert into #nome values ('ADRIANA BONFIM DOS SANTOS')
insert into #nome values ('ADRIANA CARITA TELLES DUARTE')
insert into #nome values ('ADRIANA P LAURENTI COELHO')
insert into #nome values ('ADRIANO JOSE CAMILOTE')
insert into #nome values ('ADRIEL DE SOUZA LOPES')
insert into #nome values ('AFONSO DE JESUS RIBEIRO')
insert into #nome values ('AGENOR SPERGE FILHO')
insert into #nome values ('AGNALDO CARDOSO')
insert into #nome values ('AGUINALDO MARTONI')
insert into #nome values ('AILTON CLIBAS FERRAZ DE CAMPOS')
insert into #nome values ('AILTON ROCHA LEITE')
insert into #nome values ('AISLAN ALFREDO NASCIMENTO SANTOS')
insert into #nome values ('AKEMI KURAMOCHI SAITO')
insert into #nome values ('ALAN ALFREDO DO NASCIMENTO SANTOS')
insert into #nome values ('ALAN DA SILVA RIBEIRO')
insert into #nome values ('ALAN SANTOS ROCHA DA SILVA')
insert into #nome values ('ALANA SAMARA FRACALOSSI CORDEIRO')
insert into #nome values ('ALCIDES JOSE VIEIRA')
insert into #nome values ('ALCIONE PEREIRA')
insert into #nome values ('ALDAGIZA MARIA JOIA')
insert into #nome values ('ALESSANDRA APARECIDA ARAUJO DE SOUZA')
insert into #nome values ('ALESSANDRA BATISTA DE SOUSA')
insert into #nome values ('ALESSANDRA GRASSI CLEMENCIO OLIVEIRA')
insert into #nome values ('ALESSANDRA TAGUATINGA BATISTA')
insert into #nome values ('ALESSANDRO MARCIO PISSOCO')
insert into #nome values ('ALEX SANDER PEREIRA DA SILVA')
insert into #nome values ('ALEXANDRE GALHARDO NOGUEIRA')
insert into #nome values ('ALEXANDRE IRINEU DA SILVA')
insert into #nome values ('ALEXANDRE JULIARDI DE SOUZA SOGGIA')
insert into #nome values ('ALEXANDRE MALHEIRO FERREIRA')
insert into #nome values ('ALEXANDRE MARCIANO DE FREITAS')
insert into #nome values ('ALEXANDRE MARTONI')
insert into #nome values ('ALEXANDRE MENEGHINI')
insert into #nome values ('ALEXANDRE PAULINO DA SILVA')
insert into #nome values ('ALEXANDRE ROSA PEREIRA')
insert into #nome values ('ALEXANDRO FERMIANO')
insert into #nome values ('ALINE ALVES FEITOSA')
insert into #nome values ('ALINE ELOISA GARBIN VILELA')
insert into #nome values ('ALINE GONCALVES RODRIGUES')
insert into #nome values ('ALINE PATRICIA  ALVES')
insert into #nome values ('ALINE SOARES DE SOUZA')
insert into #nome values ('ALISSON MARONEZI VIEIRA')
insert into #nome values ('ALZIRA NERY LOUREIRO')
insert into #nome values ('AMANDA FERREIRA DA SILVA')
insert into #nome values ('AMANDA FERREIRA R. DA SILVA')
insert into #nome values ('AMANDA MARIA DO NASCIMENTO SANTOS')
insert into #nome values ('AMANDA SILVONI VIEIRA')
insert into #nome values ('AMAURY VILAR DE ASSIS')
insert into #nome values ('ANA CAROLINA A CARDOSO')
insert into #nome values ('ANA LAURA APOLINARIO PEREIRA')
insert into #nome values ('ANA LUIZA VINHAS RIBEIRO')
insert into #nome values ('ANA MARIA LOUZADA FERREIRA')
insert into #nome values ('ANA MARIA TREVISAN DOS SANTOS')
insert into #nome values ('ANA PAULA ALVES DOS SANTOS')
insert into #nome values ('ANA PAULA GARCIA ')
insert into #nome values ('ANA PAULA PEREIRA AUGUSTO')
insert into #nome values ('ANA PAULA THOMAZ DE AQUINO FRARE')
insert into #nome values ('ANA PAULA VARGAS DE MELLO')
insert into #nome values ('ANA VICTORIA SANTANA EUGENIO')
insert into #nome values ('ANDERSON ALTAIR GARCIA')
insert into #nome values ('ANDERSON ANTONIO FERNANDES')
insert into #nome values ('ANDERSON DA SILVA OLIVEIRA')
insert into #nome values ('ANDERSON LAUDI PAVAN')
insert into #nome values ('ANDERSON RAFAEL DA SILVA')
insert into #nome values ('ANDERSON SAQUETO')
insert into #nome values ('ANDRE LUIS DE CARVALHO')
insert into #nome values ('ANDRE SANTOS ROCHA DA SILVA')
insert into #nome values ('ANDREA BARBOSA TRENTIN SANTOS')
insert into #nome values ('ANDREA LYRA DA SILVA')
insert into #nome values ('ANDREIA HELENA PERIM DA SILVA')
insert into #nome values ('ANDREIA VERISSIMO DOS SANTOS')
insert into #nome values ('ANDREY ERICK DE MELO')
insert into #nome values ('ANDRIGO DONIZETTI DOS SANTOS')
insert into #nome values ('ANGELA MARIA GALLO')
insert into #nome values ('ANGELA SANTOS DA CONCEICAO')
insert into #nome values ('ANGELICA APARECIDA DA SILVA OLIVEIRA')
insert into #nome values ('ANGELICA FELONI')
insert into #nome values ('ANGELICA LISBOA CESARIO')
insert into #nome values ('ANGELINO RIPOLI')
insert into #nome values ('ANGELITA APARECIDA ROCHA FERREIRA')
insert into #nome values ('ANGELO MATEUS RIPOLI')
insert into #nome values ('ANGELO MATEUS SILVA')
insert into #nome values ('ANOEL LUIZ')
insert into #nome values ('ANTONIA ANDREIA FERREIRA SILVA')
insert into #nome values ('ANTONIO CARLOS B FERNANDES DOS SANTOS')
insert into #nome values ('ANTONIO CARLOS DA SILVA')
insert into #nome values ('ANTONIO CARLOS DE SOUZA')
insert into #nome values ('ANTONIO CARLOS GONZALES ')
insert into #nome values ('ANTONIO CARLOS MARTINS NETO')
insert into #nome values ('ANTONIO CARLOS MARTINS VAQUES')
insert into #nome values ('ANTONIO CARLOS VIGATTO')
insert into #nome values ('ANTONIO DOS SANTOS NUNES JUNIOR')
insert into #nome values ('ANTONIO JOSE DA SILVA')
insert into #nome values ('ANTONIO MARCOS DE BONITO')
insert into #nome values ('ANTONIO MARCOS FERREIRA DE SOUZA')
insert into #nome values ('ANTONIO MARCOS ZERBA')
insert into #nome values ('ANTONIO NAZARENO PAIVA JUNIOR')
insert into #nome values ('APARECIDO DONIZETE AUGUSTO')
insert into #nome values ('APARECIDO GOMES DE SANTANA')
insert into #nome values ('ARIANA PEIXOTO CAMARGO')
insert into #nome values ('ARIANNE STEPHANIE COLUCCI DE PAULA')
insert into #nome values ('ARIOVALDO ALVES DA SILVA')
insert into #nome values ('AROLDO DOS SANTOS')
insert into #nome values ('AUDRY CRISTINA ANNUNCIATO')
insert into #nome values ('BARBARA SENTANIN')
insert into #nome values ('BEATRIS APARECIDA DA SILVA')
insert into #nome values ('BEATRIZ GOUVEA ALARCON')
insert into #nome values ('BENEDITO ALVES DA SILVA')
insert into #nome values ('BIANCA F.  MATEUSE')
insert into #nome values ('BIANCA MOREIRA CUBAS')
insert into #nome values ('BRENDA PALOMA RAMALHO DA SILVA')
insert into #nome values ('BRENO TELLES DUARTE ALVES')
insert into #nome values ('BRUNA CHAVES SILVA')
insert into #nome values ('BRUNA DE OLIVEIRA VIEIRA')
insert into #nome values ('BRUNA FABIOLA RODRIGUES LUZ')
insert into #nome values ('BRUNA RAMALHO DA SILVA')
insert into #nome values ('BRUNA SILVA JUSTINIANO')
insert into #nome values ('BRUNO ALEX DOS SANTOS')
insert into #nome values ('BRUNO AUGUSTO MOTTA ROSA')
insert into #nome values ('BRUNO FERNANDO CATOSSI MARTINS')
insert into #nome values ('BRUNO HENRIQUE MARIGUETI')
insert into #nome values ('BRUNO HENRIQUE PEREIRA')
insert into #nome values ('BRUNO TADSI HATANO')
insert into #nome values ('CAIO CESAR AUGUSTO ')
insert into #nome values ('CAIO EMMANUEL DE SOUZA LIMA')
insert into #nome values ('CAIO HENRIQUE DE SOUZA SANTOS')
insert into #nome values ('CAMILA DA SILVA RUFINO')
insert into #nome values ('CAMILA FERNANDA COSTA DA SILVA')
insert into #nome values ('CAMILA NAIARA PIENECONTA')
insert into #nome values ('CARINA AMARANTE PEDERSOLI')
insert into #nome values ('CARLA CRISTINE S. E SILVA')
insert into #nome values ('CARLA DA SILVA CRUZ SOARES')
insert into #nome values ('CARLA DA SILVA PEREIRA')
insert into #nome values ('CARLA VICENTE SOARES')
insert into #nome values ('CARLOS ANDRE ALMEIDA DE MELO')
insert into #nome values ('CARLOS EDUARDO CHIARETTI')
insert into #nome values ('CARLOS EDUARDO DA SILVA')
insert into #nome values ('CARLOS EDUARDO REIS ARCAS')
insert into #nome values ('CARLOS FERREIRA')
insert into #nome values ('CARLOS ROBERTO ARCAS')
insert into #nome values ('CARLOS ROBERTO MANOEL')
insert into #nome values ('CARLOS RONNIER BARRETO PECANHA')
insert into #nome values ('CARMEM APARECIDA INACIO')
insert into #nome values ('CAROLINA V V ALMADA N FERNANDES')
insert into #nome values ('CAROLINE LEONCIO')
insert into #nome values ('CELIA SPERGE')
insert into #nome values ('CELSO HENRIQUE SOARES')
insert into #nome values ('CELSO IGNACIO GASPAR')
insert into #nome values ('CESAR AUGUSTO ARANTES')
insert into #nome values ('CHRISTIAN GABRIEL CARDOZO')
insert into #nome values ('CILERINA DOS SANTOS PORTO BRITO')
insert into #nome values ('CINTIA A K DE MORAES ZAMBONI')
insert into #nome values ('CIRLENE MARQUES JARDIM')
insert into #nome values ('CLAUDENICE ALVES FULAS')
insert into #nome values ('CLAUDIA AMELIA MARONEZI')
insert into #nome values ('CLAUDIA GOUVEIA ALARCON ')
insert into #nome values ('CLAUDIA REBECA SERVO DE JESUS')
insert into #nome values ('CLAUDIANA FRANCISCO BORGES')
insert into #nome values ('CLAUDIO CELSO MARQUES DE OLIVEIRA')
insert into #nome values ('CLAUDIO DA SILVA SOUZA')
insert into #nome values ('CLAUDIO LUIS ROXA')
insert into #nome values ('CLAUDIO LUIZ APARECIDO PUYA ')
insert into #nome values ('CLAYTON DE FARIA')
insert into #nome values ('CLAYTON GOMES')
insert into #nome values ('CLEITON PERES DA CUNHA')
insert into #nome values ('CLERISTON DE FARIA')
insert into #nome values ('CLODOALDO DE PAULA ARAUJO')
insert into #nome values ('CLODOALDO ROSA')
insert into #nome values ('CONCEICAO APARECIDA DE MELO')
insert into #nome values ('CONCEICAO APARECIDA MIRANDA DE ASSIS')
insert into #nome values ('CONCEICAO APARECIDA SILVONI VIEIRA')
insert into #nome values ('CORNELIO SIMOES GONSALES')
insert into #nome values ('COSME CESAR DE JESUS')
insert into #nome values ('COSMO GAIA DA SILVA')
insert into #nome values ('CRISPIM SANTA ROSA DOS SANTOS')
insert into #nome values ('CRISTIANA MAIA')
insert into #nome values ('CRISTIANE APARECIDA ROSSINI OLIVEIRA')
insert into #nome values ('CRISTIANE FALEINOS MARTINS')
insert into #nome values ('CRISTIANE SOARES SILVA ')
insert into #nome values ('CRISTIANO CELIO MOREIRA F DA SILVA')
insert into #nome values ('CRISTIANO SERAFIM DA CRUZ')
insert into #nome values ('CRISTINA APARECIDA BORGES DA SILVA')
insert into #nome values ('CRISTINA DA SILVA BEZERRA')
insert into #nome values ('DAGMAR APARECIDA REGES CAMPOS')
insert into #nome values ('DAIANA SUELY PEREIRA')
insert into #nome values ('DAIANE CHAVES SILVA')
insert into #nome values ('DAIVA BEZERRA DA SILVA')
insert into #nome values ('DALIANE BALBINO DA COSTA')
insert into #nome values ('DALVA MENEGHESS')
insert into #nome values ('DANIEL CARLOS BARBOSA SOARES')
insert into #nome values ('DANIEL JUNIO DE LACERDA IMBRONI')
insert into #nome values ('DANIEL NOMELLINI')
insert into #nome values ('DANIEL RUFINO DE SOUZA')
insert into #nome values ('DANIEL SANN MOURAO ALMEIDA')
insert into #nome values ('DANIELA ANELI ABDALA')
insert into #nome values ('DANIELA APARECIDA QUINTINO')
insert into #nome values ('DANIELA BORGES')
insert into #nome values ('DANIELA DAVINI')
insert into #nome values ('DANIELA FERNANDA A. FELIX PEREIRA')
insert into #nome values ('DANIELA YUMY SAITO')
insert into #nome values ('DANIELE PRISCILA PASTRELLO')
insert into #nome values ('DANILO GOMES DOS SANTOS')
insert into #nome values ('DAVI OTTOBONI')
insert into #nome values ('DAYANA KARLA DE BRITTO')
insert into #nome values ('DEBORAH CINARA SILVA')
insert into #nome values ('DEMETRIO PUPOLIN')
insert into #nome values ('DENIS ALEXANDRE DOS REIS')
insert into #nome values ('DENIS FIRMINO DA SILVA')
insert into #nome values ('DEUSINHO DE SOUZA CAETANO')
insert into #nome values ('DIEGO MACIEL MAGOLLO')
insert into #nome values ('DIEGO MOURA MARTINS ')
insert into #nome values ('DIEGO PEREIRA DOS SANTOS')
insert into #nome values ('DIONICE C MARQUES ')
insert into #nome values ('DORY MICHEL ABDOU')
insert into #nome values ('DOUGLAS CRUZ DE FARIA')
insert into #nome values ('DOUGLAS RIBEIRO DE LIMA')
insert into #nome values ('DOUGLAS SOGGIA DA SILVA')
insert into #nome values ('DRIELI MARONEZI VIEIRA')
insert into #nome values ('EDGARD FERREIRA PRACHEDES')
insert into #nome values ('EDIGAR CARIAGA LOPES')
insert into #nome values ('EDILAIDO RODRIGUES DE SALES')
insert into #nome values ('EDISON CRISTOVAN RAMOS')
insert into #nome values ('EDIVALDO BERTUOLO JUNIOR ')
insert into #nome values ('EDMAR PERES CORDEIRO')
insert into #nome values ('EDMILSON PEREZ CORDEIRO')
insert into #nome values ('EDNA VIEIRA JORGE')
insert into #nome values ('EDNALVA SANTA ROSA DA SILVA EVANGELISTA')
insert into #nome values ('EDNILSON MENDES PEREIRA')
insert into #nome values ('EDSON LUIZ ')
insert into #nome values ('EDUARDA COELHO CHIQUITELLI')
insert into #nome values ('EDUARDO CARMO BASILIO')
insert into #nome values ('EDUARDO MAIMONE AGUILLAR')
insert into #nome values ('ELAINE APARECIDA FAGUNDES')
insert into #nome values ('ELAINE CRISTINA DOS SANTOS ARAUJO')
insert into #nome values ('ELAINE CRISTINA LUIZ RODRIGUES')
insert into #nome values ('ELCIO SOUZA MARQUES')
insert into #nome values ('ELDER APARECIDO DE OLIVEIRA')
insert into #nome values ('ELIANA AP C DA CAMARA ')
insert into #nome values ('ELIANE SILVEIRA')
insert into #nome values ('ELIANE SILVERIO')
insert into #nome values ('ELIAS MIGUEL DA SILVA JUNIOR')
insert into #nome values ('ELIZABETE SILVA PINHEIRO RODRIGUES')
insert into #nome values ('ELIZABETH RAQUEL BORGES')
insert into #nome values ('ELIZANDRA MARTONI')
insert into #nome values ('ELKE TIEGUI BALDO')
insert into #nome values ('ELOISA SILVA CAMPOS')
insert into #nome values ('ELY JUNIOR RIBEIRO SILVA')
insert into #nome values ('EMILIANA AP DE OLIVEIRA')
insert into #nome values ('EMILIANA DE OLIVEIRA ALMEIDA')
insert into #nome values ('ENEDINA DA SILVA')
insert into #nome values ('ERIKA ROBERTA SANTOS')
insert into #nome values ('ERIVALDO DE JESUS FERNANDEZ')
insert into #nome values ('ESTEFANIA XAVIER COSTA')
insert into #nome values ('EUNICE AP DE LACERDA IMBROZIO')
insert into #nome values ('EURICO JOSE SANTOS')
insert into #nome values ('EURIPEDES VIEIRA DE OLIVEIRA')
insert into #nome values ('EUZIVALDA DE OLIVEIRA VIEIRA')
insert into #nome values ('EVANDRO CESAR DOS SANTOS')
insert into #nome values ('EVERTON ALEX JUNIOR PEREIRA DE CARVALHO')
insert into #nome values ('EWISTER RODRIGUES BARBONI')
insert into #nome values ('EZEQUIEL BATISTA')
insert into #nome values ('EZEQUIEL RUFINO DE SOUZA')
insert into #nome values ('FABIANA ALGARTE PIRES CORDEIRO')
insert into #nome values ('FABIANA F. MATEUSE')
insert into #nome values ('FABIANA MARTINS DE OLIVEIRA')
insert into #nome values ('FABIANE DANIELA BARBONI')
insert into #nome values ('FABIANO ALVES PINTO')
insert into #nome values ('FABIO ADRIANO DOS SANTOS FAUSTINO')
insert into #nome values ('FABIO APARECIDO DE OLIVEIRA')
insert into #nome values ('FABIO AUGUSTO VIGNA')
insert into #nome values ('FABIO DAVINI')
insert into #nome values ('FABIO DE ALMEIDA FERNANDES')
insert into #nome values ('FABIO MELO DA SILVA')
insert into #nome values ('FABIO RODRIGUES NIGRO ')
insert into #nome values ('FABIO VIANELLO')
insert into #nome values ('FABIO WANDEL FRANCO')
insert into #nome values ('FABRICIO HENRIQUE ZILLI')
insert into #nome values ('FABRICIO MARCELO DOS SANTOS FAUTISNO')
insert into #nome values ('FATIMA DE JESUS SILVA RIPOLI ')
insert into #nome values ('FATIMA MARTINS DA SILVA')
insert into #nome values ('FELIPPE PALMEIRA MELOS')
insert into #nome values ('FERNANDA COSTA PEREIRA LULA')
insert into #nome values ('FERNANDA DE OLIVEIRA GARCIA')
insert into #nome values ('FERNANDO ALMEIDA SAMPAIO')
insert into #nome values ('FERNANDO ASSAGRA')
insert into #nome values ('FERNANDO CESAR RODRIGUES')
insert into #nome values ('FERNANDO HENRIQUE BOIAN')
insert into #nome values ('FLAVIA DE LIMA MOLESINI')
insert into #nome values ('FLAVIO LUIZ DA SILVA')
insert into #nome values ('FLORISVALDO ALVES DOS SANTOS')
insert into #nome values ('FRANCIELE AP DA S DE SOUZA')
insert into #nome values ('FRANCIELE AP DA S SOUZA')
insert into #nome values ('FRANCIELE APARECIDA DE OLIVEIRA')
insert into #nome values ('FRANCINI LINO BORBA')
insert into #nome values ('FRANCISCO CARLOS W. GOMES')
insert into #nome values ('FRANCISCO ECLIBERTO SILVA')
insert into #nome values ('GABRIEL ANSANELLO DE FARIA')
insert into #nome values ('GABRIEL ARAUJO A DE SOUZA')
insert into #nome values ('GABRIEL CAMARGO NORBERTO ')
insert into #nome values ('GABRIEL HENRIQUE ROSSINI OLIVEIRA')
insert into #nome values ('GABRIELA  DIAS')
insert into #nome values ('GABRIELA RAMOS MELLO ')
insert into #nome values ('GABRIELA TRENTIN DOS SANTOS')
insert into #nome values ('GABRIELY APARECIDA ARCAS SANTOS')
insert into #nome values ('GECILDA BATISTA PEREIRA')
insert into #nome values ('GENERCI MICHELI MENESES')
insert into #nome values ('GENI ALVES DE SOUZA')
insert into #nome values ('GERSON VITORIO FARNOCCHI')
insert into #nome values ('GICELIA RAMALHO DA SILVA')
insert into #nome values ('GILBERTO DA CAMARA')
insert into #nome values ('GIOVANA DA SILVA GODOI')
insert into #nome values ('GIOVANNA ZIPPARRO')
insert into #nome values ('GISELE MARTINS VAQUES')
insert into #nome values ('GLAUCIELE FERREIRA BENITES')
insert into #nome values ('GLAUCO CERRI DE CAMPOS')
insert into #nome values ('GUERINO AUGUSTO DE SOUZA')
insert into #nome values ('GUILHERME FERNANDO DIAS RODRIGUES')
insert into #nome values ('GUILHERME HENRIQUE DOS SANTOS')
insert into #nome values ('GUILHERME HENRIQUE MOTTA ROSA')
insert into #nome values ('GUILHERME VINICIUS DE CASTRO')
insert into #nome values ('GULHERME MARTINS DE PAIVA')
insert into #nome values ('GUMERCINDA OLIVEIRA GARCIA')
insert into #nome values ('GUSTAVO BEZERRA HESPANHA')
insert into #nome values ('GUSTAVO DOS SANTOS OLIVEIRA')
insert into #nome values ('GUSTAVO LUIS DE MORAIS FERREIRA')
insert into #nome values ('GUSTAVO MARTINS DE PAIVA')
insert into #nome values ('GUSTAVO NOVARI DE LIMA')
insert into #nome values ('GUSTAVO SILVA OLIVEIRA')
insert into #nome values ('GUTIERRES AMERICO DE OLIVEIRA')
insert into #nome values ('HELENA CARDOSO AGUILLAR')
insert into #nome values ('HELOISA APARECIDA ALVES')
insert into #nome values ('HENRIQUE PINTO')
insert into #nome values ('HERBERT LUIZ THEOTONIO DA COSTA ')
insert into #nome values ('HERCILDA MENDES BATISTA')
insert into #nome values ('HERIK FELIPE SANTOS BISPO')
insert into #nome values ('HILDA HELENA FERREIRA VIEIRA')
insert into #nome values ('HUGO LEANDRO DA SILVA')
insert into #nome values ('HUMBERTO JUNIOR DOS S SANTANA')
insert into #nome values ('IARA APARECIDA GOMES')
insert into #nome values ('ILCELENE MARCIA DE BRITO')
insert into #nome values ('ILENE MARIA TEIXEIRA COSTA')
insert into #nome values ('ILMA ALVES DE MACEDO ALMEIDA')
insert into #nome values ('INGRID KETLYN SOUZA SANTOS')
insert into #nome values ('INGRID LETICIA GONCALVES CAMARGO NORBERT')
insert into #nome values ('ISABEL CRISTINA DE SOUZA')
insert into #nome values ('ISABELA DE OLIVEIRA DA SILVA')
insert into #nome values ('ISABELA TRENTIN DOS SANTOS')
insert into #nome values ('ISABELLA FRANCA MOREIRA')
insert into #nome values ('ISABELLY PIZZE DA SILVA')
insert into #nome values ('IVANILDA DANTAS SILVA')
insert into #nome values ('IVETE DA SILVA ALVES')
insert into #nome values ('IVO ANTONIO ALVES JUNIOR')
insert into #nome values ('IVONEIDE APARECIDA ALVES DA SILVA')
insert into #nome values ('IZABEL DE FATIMA CESARIO AMARAL')
insert into #nome values ('IZABEL NUNES DA SILVA')
insert into #nome values ('IZABELLA IMBROZIO DA SILVA')
insert into #nome values ('IZAIRA CAMARGO')
insert into #nome values ('IZAQUE RUFINO DE SOUZA')
insert into #nome values ('JAIR GOMES NOGUEIRA')
insert into #nome values ('JAKELINE HELLEN ADAO')
insert into #nome values ('JANAINA OLIVEIRA COSTA ')
insert into #nome values ('JANAINA PEREIRA ANUNCIO')
insert into #nome values ('JAQUELINE CARLA DOS SANTOS SOUZA')
insert into #nome values ('JAQUELINE KELLY CANGUSSU PALMEIRA')
insert into #nome values ('JAQUELINE PATRICIA BANDEIRA')
insert into #nome values ('JAQUELINE PEDROSO LUIZ')
insert into #nome values ('JEAN CARLOS DE SOUZA OLIVEIRA')
insert into #nome values ('JEAN LUIZ BIANCHI')
insert into #nome values ('JEAN MARCEL DA SILVA ALVES')
insert into #nome values ('JEAN RICARDO TROCHINSKI')
insert into #nome values ('JEFFERSON DIAS')
insert into #nome values ('JEFFERSON DIAS FILHO')
insert into #nome values ('JEFFERSON RICARDO OTTOBONI')
insert into #nome values ('JENIFFER BIBIANI LUIS TEIXEIRA')
insert into #nome values ('JENNIFER CAROLINE O DE CARVALHO')
insert into #nome values ('JEREMIAS NOGUEIRA JUNS')
insert into #nome values ('JESSICA CRISTINA DO PRADO RODRIGUES')
insert into #nome values ('JESSICA DA SILVA ALVARES')
insert into #nome values ('JESSICA LOIOLA DOS SANTOS')
insert into #nome values ('JESUS CORDEIRO RODRIGUES GODOY')
insert into #nome values ('JHONI HENRIQUE DE JESUS')
insert into #nome values ('JOANA D ARC GOMES MONTEIRO')
insert into #nome values ('JOANA MARIA ALVES DA SILVA')
insert into #nome values ('JOAO CARLOS A SILVA CURVO')
insert into #nome values ('JOAO DE OLIVEIRA')
insert into #nome values ('JOAO JOSE DA SILVEIRA')
insert into #nome values ('JOAO LUCAS CORDEIRO FERREIRA DOS SANTOS')
insert into #nome values ('JOÃO LUIZ CONSTANTINO')
insert into #nome values ('JOAO LUIZ DA SILVA NETO')
insert into #nome values ('JOAO MARCELO ISIDORO FIGUEREIDO')
insert into #nome values ('JOAO PEDRO DE ALMEIDA FERNANDES')
insert into #nome values ('JOAO PEDRO EUGENIO')
insert into #nome values ('JOAO VICTOR DA SILVA GODOY')
insert into #nome values ('JOAO VICTOR ROSSINI OLIVEIRA')
insert into #nome values ('JOAO VICTOR TEIXEIRA')
insert into #nome values ('JOAO VITOR BATISTA TAVARES')
insert into #nome values ('JOAO VITOR TRENTIN DOS SANTOS')
insert into #nome values ('JOAQUIM ANTONIO DOS REIS')
insert into #nome values ('JOAQUIM FRANCISCO DE MORAES ZAMBONI')
insert into #nome values ('JOAQUIM ISIDORO DA SILVA')
insert into #nome values ('JOCELENE ALVES DA SILVA')
insert into #nome values ('JOCESLAINE AP CATOSSI')
insert into #nome values ('JOHN APARECIDO DE SILVA')
insert into #nome values ('JOILSON SANTOS SILVA')
insert into #nome values ('JONAS FERNANDES DOS SANTOS')
insert into #nome values ('JONATHAN PUYA')
insert into #nome values ('JONATHAN TERESIANO D. CAMPOS VENANCIO')
insert into #nome values ('JORDANA DA SILVA APOLINARIO')
insert into #nome values ('JORDANA DE OLIVEIRA')
insert into #nome values ('JORGE AUGUSTO ALVES DA SILVA')
insert into #nome values ('JORGE DOS REIS DE SOUZA')
insert into #nome values ('JORGE LUIS BORTOLIN')
insert into #nome values ('JORGE LUIS M. BORTOLIN')
insert into #nome values ('JORGE PAULO PEREIRA SOUZA')
insert into #nome values ('JOSE ALVES')
insert into #nome values ('JOSE APARECIDO LOFRANO')
insert into #nome values ('JOSE AUGUSTO DA SILVA SANTOS')
insert into #nome values ('JOSE CARLOS SALGADO')
insert into #nome values ('JOSE CLAUDIO CATISTI DE SEIXAS ')
insert into #nome values ('JOSE EDUARDO BRAGA')
insert into #nome values ('JOSE EDUARDO GOMES')
insert into #nome values ('JOSE EDUARDO MARITAN')
insert into #nome values ('JOSE FLAVIO SPIRANDELLI')
insert into #nome values ('JOSE IBRAIM BARBOSA HAYASHIDA')
insert into #nome values ('JOSE LUIZ BIANCHI')
insert into #nome values ('JOSE MENDES DA SILVA')
insert into #nome values ('JOSE MESSIAS LAURIANO DE ANDRADE')
insert into #nome values ('JOSE PAULO BOIAN')
insert into #nome values ('JOSE PEREIRA DA SILVA')
insert into #nome values ('JOSE URIAS DE OLIVEIRA')
insert into #nome values ('JOSE WAGNER FERREIRA')
insert into #nome values ('JOSE WILSON RODRIGUES DA SILVA')
insert into #nome values ('JOSEFA MARIA SANTANA BIANCHI')
insert into #nome values ('JOSIANE DA SILVA TEIXEIRA')
insert into #nome values ('JOSIANI PATRICIA PIZZE DA SILVA')
insert into #nome values ('JOSIMAR BANDEIRA')
insert into #nome values ('JUCIRA SILA OLIVEIRA')
insert into #nome values ('JULIA BUZZO CHINARELLO')
insert into #nome values ('JULIA DA SILVA MARQUES')
insert into #nome values ('JULIA MARIA RODRIGUES LUZ')
insert into #nome values ('JULIA MARTINS LEITE')
insert into #nome values ('JULIA ROBERTO DOS REIS')
insert into #nome values ('JULIANA ANDRADE BEZERRA')
insert into #nome values ('JULIANA APARECIDA MARTINS CARDOZO')
insert into #nome values ('JULIANA DE FREITAS ARAUJO')
insert into #nome values ('JULIANA LUZ')
insert into #nome values ('JULIANA MISLENE PEREIRA')
insert into #nome values ('JULIANA ROSA DA SILVA')
insert into #nome values ('JULIANO HENRIQUE FERMINO')
insert into #nome values ('JULIANO LUIZ DA SILVA')
insert into #nome values ('JULIANO MOREIRA ')
insert into #nome values ('JULIO CARLOS MARCHIORI')
insert into #nome values ('JULIO CESAR DOS REIS ZAMBONI')
insert into #nome values ('JULIO CESAR OLIVEIRA GARCIA')
insert into #nome values ('JUNIO CESAR MATEUSE')
insert into #nome values ('KAILANE ALVES DA SILVA')
insert into #nome values ('KAMILLA SINIBALDI')
insert into #nome values ('KAREN VITORIA RECCHIA PEREIRA')
insert into #nome values ('KARINA APARECIDA URIAS BONAVINA')
insert into #nome values ('KARINA SAGIORATO DIAS TOMAZ')
insert into #nome values ('KARINA TARGA DIAS')
insert into #nome values ('KARINE LIMA MILHOMEM')
insert into #nome values ('KATIA REGINA PORTELLA')
insert into #nome values ('KAUA DE JESUS CANDIDO')
insert into #nome values ('KAUA LEONARDO B FERNANDES DOS SANTOS')
insert into #nome values ('KAUAN BERZUINO MACHADO')
insert into #nome values ('KAUE HENRIQUE BUENO FERNANDES DOS SANTOS')
insert into #nome values ('KAVANA GABRIELA LOFRANO')
insert into #nome values ('KAYCK DE MELLO ALVES')
insert into #nome values ('KEILY CILMARA RODRIGUES')
insert into #nome values ('KIMBERLLY CAROLINE FELIX DA SILVA')
insert into #nome values ('KLEBER CAPELARI')
insert into #nome values ('KLEBER LUIZ MOVIO')
insert into #nome values ('KLEITON ROCHA DA SILVA')
insert into #nome values ('LAIS ARANDA FACCHIN')
insert into #nome values ('LAODICEIA APARECIDA DE OLIVEIRA')
insert into #nome values ('LARA KELLY PALMEIRA LEMOS')
insert into #nome values ('LARISSA APARECIDA MOTTA ROSA')
insert into #nome values ('LARISSA CHRISTINA B ROSA')
insert into #nome values ('LARISSA OLIVEIRA DA SILVA')
insert into #nome values ('LAURA KELSYN DA SILVA CAPELARI')
insert into #nome values ('LEANDRA DE PAULA BERNADINI')
insert into #nome values ('LEANDRO AUGUSTO COSTA DE OLIVEIRA')
insert into #nome values ('LEANDRO DA SILVA SANTANA')
insert into #nome values ('LEANDRO OLIVEIRA DOS SANTOS')
insert into #nome values ('LEANDRO PERES ALTINO')
insert into #nome values ('LECIR FERREIRA DE OLIVEIRA')
insert into #nome values ('LEIDIVANIA CARVALHO EUGENIO')
insert into #nome values ('LEONARDO BORGES')
insert into #nome values ('LEONARDO DIAS TEIXEIRA JUNIOR')
insert into #nome values ('LEONARDO HENRIQUE DE BONITO')
insert into #nome values ('LEONICE NUNES LEMES')
insert into #nome values ('LETICIA APARECIDA BITELLA ALVES')
insert into #nome values ('LETICIA CRISTINA FERREIRA')
insert into #nome values ('LETICIA SILVA VIANNA')
insert into #nome values ('LEVY FERREIRA JUNIOR')
insert into #nome values ('LIDIANE LEAL SILVEIRA')
insert into #nome values ('LIGIA CARMEN DA SILVA')
insert into #nome values ('LIGIA FERNANDA PEREDO')
insert into #nome values ('LINCOLN JOSE CERDEIRA')
insert into #nome values ('LINCON GUILHERME ARCAS SANTOS')
insert into #nome values ('LIVIA REIS DE SOUSA')
insert into #nome values ('LOURDES DA SILVA GASPAR')
insert into #nome values ('LOURENCO CARDOSO AGUILLAR')
insert into #nome values ('LOURIVANDA FERREIRA DA SILVA')
insert into #nome values ('LUAISIS ROBERTO REZENDI')
insert into #nome values ('LUANA PEREIRA DE SOUZA')
insert into #nome values ('LUCAS BRUNO DA SILVA')
insert into #nome values ('LUCAS DE SOUZA MARITAN')
insert into #nome values ('LUCAS EDUARDO FELIPE MACHADO')
insert into #nome values ('LUCAS RAFAEL JARDIM')
insert into #nome values ('LUCAS SAGIORATO COSTA SOBRAL')
insert into #nome values ('LUCAS SILVA OLIVEIRA')
insert into #nome values ('LUCIA HELENA BELLISSIMO')
insert into #nome values ('LUCIANA REGINA REIS ARCAS SANTOS')
insert into #nome values ('LUCIANA RIBEIRO')
insert into #nome values ('LUCIANE C. G. BORTOLIN')
insert into #nome values ('LUCIANO DONIZETE GEISDRF')
insert into #nome values ('LUCICLEIA LEITE PEREIRA')
insert into #nome values ('LUCIENE BATISTA MENDES')
insert into #nome values ('LUCIENE LEITE PEREIRA')
insert into #nome values ('LUCIMAR APARECIDA PEREIRA SOARES')
insert into #nome values ('LUES ALBERTO RIGOBELE SILVA')
insert into #nome values ('LUIS CARLOS FERREIRA')
insert into #nome values ('LUIS CARLOS ROMERO TEIXEIRA')
insert into #nome values ('LUIS SAMUEL TEIXEIRA DIAS ')
insert into #nome values ('LUIZ AGNALDO DUPIM')
insert into #nome values ('LUIZ ALBERTO FERREIRA')
insert into #nome values ('LUIZ ANTONIO CORRAL')
insert into #nome values ('LUIZ ANTONIO SENTANIN')
insert into #nome values ('LUIZ CARLOS ALARCON ALMEIDA')
insert into #nome values ('LUIZ CARLOS NUNES BALBINO')
insert into #nome values ('LUIZ DONIZETE SOGGIA')
insert into #nome values ('LUIZ HENRIQUE IGNACIO JUNIOR')
insert into #nome values ('LUIZ PASCHOAL GUIDOZI')
insert into #nome values ('LUIZA PAULA FERREIRA BARBOSA')
insert into #nome values ('MAGALI FERNANDES DA SILVA')
insert into #nome values ('MAIARA DALLA MARTHA')
insert into #nome values ('MAITE MIRIAN RIBEIRO DE OLIVEIRA')
insert into #nome values ('MANOEL NUNES DE OLIVEIRA FILHO')
insert into #nome values ('MANOEL TADEU DE CARVALHO MARTINS')
insert into #nome values ('MARCEL TIAGO GUERRINE PASTORE')
insert into #nome values ('MARCELA CARLA DE CASTRO')
insert into #nome values ('MARCELO ALEXANDRE BASTOS')
insert into #nome values ('MARCELO D COELHO')
insert into #nome values ('MARCELO GOUVEA CAJUEIRO')
insert into #nome values ('MARCELO HENRIQUE S SOUZA')
insert into #nome values ('MARCELO PESTANA')
insert into #nome values ('MARCELO SILVEIRA RODRIGUES')
insert into #nome values ('MARCIA MARIA DE QUEIROZ CARDOSO')
insert into #nome values ('MARCIA MARIA REGOBELI SILVA')
insert into #nome values ('MARCIA REGINA MINGARINO DE FIGUEIREDO')
insert into #nome values ('MARCIA RODRIGUES DE OLIVEIRA')
insert into #nome values ('MARCIO ALEXANDRE DOS SANTOS ARAUJO')
insert into #nome values ('MARCIO DE SOUZA MARITAN')
insert into #nome values ('MARCIO JOSE SOEIRA')
insert into #nome values ('MARCIO ROGERIO DE PAULA ARAUJO')
insert into #nome values ('MARCO AURELIO DE SOUSA DIAS')
insert into #nome values ('MARCO AURELIO DUARTE')
insert into #nome values ('MARCOS AURELIO MARTINS CARDOSO')
insert into #nome values ('MARCUS VINICIUS PALMEIRA LEMOS')
insert into #nome values ('MARGARIDA LUIZA DAS GRACAS')
insert into #nome values ('MARGARIDA MARIA DE JESUS')
insert into #nome values ('MARIA ANTONIA DE LIMA MARTINS')
insert into #nome values ('MARIA APARECIDA DA CRUZ')
insert into #nome values ('MARIA APARECIDA DE OLIVEIRA ALVES')
insert into #nome values ('MARIA APARECIDA DOS SANTOS GUIDORZI')
insert into #nome values ('MARIA APARECIDA MOTA DE FARIA')
insert into #nome values ('MARIA BEATRIZ DE SOUZA SOGGIA')
insert into #nome values ('MARIA CAROLINA GARCIA')
insert into #nome values ('MARIA CLAUDIA DE SEIXAS')
insert into #nome values ('MARIA DE LOURDES VIEIRA DOS SANTOS ')
insert into #nome values ('MARIA EDUARDA COSTA GOMES')
insert into #nome values ('MARIA EDUARDA DA SILVA SANTOS')
insert into #nome values ('MARIA EUGENIA ALVES MOTTA ROSA')
insert into #nome values ('MARIA HELENA AGOSTINI SENTANIN')
insert into #nome values ('MARIA INES IZIDORO')
insert into #nome values ('MARIA ISABEL MORGADO RAMOS')
insert into #nome values ('MARIA JOSE DA SILVA')
insert into #nome values ('MARIA JOSE TOCCHINI MOTTA')
insert into #nome values ('MARIA JOSE VIEIRA MARTONI')
insert into #nome values ('MARIA LAURA BITELLA ALVES')
insert into #nome values ('MARIA LUCIA VAQUES')
insert into #nome values ('MARIA REGINA FERREIRA SOEIRA')
insert into #nome values ('MARIA STEFANIA MORETTO')
insert into #nome values ('MARIA VALDIRENE NASCIMENTO CUNHA')
insert into #nome values ('MARIANA DE OLIVEIRA VIANA')
insert into #nome values ('MARIANA PASCHARELO')
insert into #nome values ('MARIANNA ALOI PINTO')
insert into #nome values ('MARILAINE DA SILVA DOS SANTOS')
insert into #nome values ('MARILDA ALOI PINTO')
insert into #nome values ('MARINALVA LOPES DE MACEDO')
insert into #nome values ('MARINEZ LEMES DO NASCIMENTO')
insert into #nome values ('MARIO AUGUSTO DE PAULA QUEROZ ')
insert into #nome values ('MARIO RAFAEL DA SILVA')
insert into #nome values ('MARISA PALARETI ')
insert into #nome values ('MARIZA CONCEICAO DA SILVA')
insert into #nome values ('MARIZA TELLES DUARTE')
insert into #nome values ('MARLENE MOREIRA DA SILVA')
insert into #nome values ('MARLI DONIZETI GARBIN VILELA')
insert into #nome values ('MARLUCIA APARECIDA DE MORAIS FERREIRA')
insert into #nome values ('MARTA MARIA DELFINO')
insert into #nome values ('MATHEUS HENRIQUE ALEXANDRE')
insert into #nome values ('MAURICIO SENTANIN')
insert into #nome values ('MAURO LUCIO FERREIRA')
insert into #nome values ('MAYARA PEREIRA ANUNCIO')
insert into #nome values ('MEIRE JULIANA SALGADO')
insert into #nome values ('MICHAEL HUGO GUIDORZI')
insert into #nome values ('MICHEL DONIZETE BRANQUINI')
insert into #nome values ('MICHELE APARECIDA LICE DOS SANTOS')
insert into #nome values ('MIKAELA ARAUJO DE SOUZA')
insert into #nome values ('MIRELLA GIOVANNA VIEIRA')
insert into #nome values ('MIRIAN DIN MORELLI IPOLITO')
insert into #nome values ('MISAEL FELONI GOMES')
insert into #nome values ('MONICA APARECIDA DA SILVA DE SOUZA')
insert into #nome values ('MURILO POTERIO BORSARO')
insert into #nome values ('MYRELLA ALVES FULAS')
insert into #nome values ('NARA DE LACERDA IMBRONIZIO')
insert into #nome values ('NATALIA FERREIRA DE ARAUJO')
insert into #nome values ('NATALIA HERMES BERZUINO MACHADO')
insert into #nome values ('NATALIA MARINA RICARDO')
insert into #nome values ('NATHALIA CAMARA')
insert into #nome values ('NATHALIE GARCIA PUPOLIN')
insert into #nome values ('NATHALY GABRIELLE N DOS SANTOS RAMOS')
insert into #nome values ('NAYARA AGNES ANTONIA FERRAZ')
insert into #nome values ('NAYARA APARECIDA MATEUS')
insert into #nome values ('NELMA CRISTINA APARECIDA DE OLIVEIRA')
insert into #nome values ('NELMA POSSIDONIO CHAVES SILVA')
insert into #nome values ('NELSON CORTEZ ZANATTO')
insert into #nome values ('NEUZA CORREA DE CARVALHO')
insert into #nome values ('NICOLAS  REZENDE DE ASSIS')
insert into #nome values ('NILCE ROSA DA S DE SOUZA')
insert into #nome values ('NILSON FERREIRA DE LIMA')
insert into #nome values ('NIVALDO CESAR DE MARTINO')
insert into #nome values ('NOEL JOAO BEZERRA')
insert into #nome values ('NOEL JOAO BEZERRA JUNIOR')
insert into #nome values ('NOEMI NUNES DA SILVA')
insert into #nome values ('OSEIAS NERY LOUREIRO')
insert into #nome values ('OSMAR DIAS TOMAS JUNIOR')
insert into #nome values ('OSVALDO SATURNINO VILELA')
insert into #nome values ('OZIRES GRAVINE')
insert into #nome values ('PABLO GEOVANE ANDRADE')
insert into #nome values ('PATRICIA AP ROSSINI FESTUCCIA')
insert into #nome values ('PATRICIA APARECIDA DE JESUS KOSZT')
insert into #nome values ('PATRICIA EVERLYN COSTA VIGATTO')
insert into #nome values ('PATRICIA MARIANA AMARAL')
insert into #nome values ('PATRICIA MINCHIO ABRAO')
insert into #nome values ('PATRICIA NUNES SILVA')
insert into #nome values ('PATRICK LUIS DOS SANTOS')
insert into #nome values ('PAULA CARDOSO SANTOS')
insert into #nome values ('PAULA TOCCHINI MOTTA')
insert into #nome values ('PAULO HENRIQUE MORILLAS')
insert into #nome values ('PEDRO ALEXANDRE DA SILVA NUNES')
insert into #nome values ('PEDRO AMARAL ')
insert into #nome values ('PEDRO ANTONIO BONIFACIO')
insert into #nome values ('PEDRO GABRIEL OTTOBONI')
insert into #nome values ('PEDRO GUILHERME MARCOLINO FARIA')
insert into #nome values ('PEDRO HENRIQUE ALVES FULAS')
insert into #nome values ('PEDRO HENRIQUE DA SILVA SANTOS')
insert into #nome values ('PEDRO HENRIQUE SILVA FERMIANO')
insert into #nome values ('PEDRO KAIQUE RODRIGUES DE CAMARGO')
insert into #nome values ('PEDRO LUIZ MONTEIRO DE FIGUEIREDO')
insert into #nome values ('PEDRO MENEZES FURIGO')
insert into #nome values ('PRISCILA APARECIDA LUCCAS')
insert into #nome values ('PRISCILA KELLY REIS ARCAS MENEGHINI')
insert into #nome values ('PRISCILA NAMY SAITO')
insert into #nome values ('PRISCILA SOARES DE ARAUJO')
insert into #nome values ('QUITERIA PEREIRA DA SILVA')
insert into #nome values ('RACHEL MARISA TOFETTI MARTINS')
insert into #nome values ('RAFAEL XIMENES')
insert into #nome values ('RAPHAEL ALOI PINTO')
insert into #nome values ('RAQUEL PUYA')
insert into #nome values ('RAUL VITOR DE MORAIS FERREIRA')
insert into #nome values ('RAYSSA LUANA SILVA PEREIRA')
insert into #nome values ('REGIANE DIAS FURTADO SILVA')
insert into #nome values ('REGIANE SILVA')
insert into #nome values ('REGINA DUARTE DA SILVA RODRIGUES')
insert into #nome values ('REINALDO FELIX DA SILVA')
insert into #nome values ('REINALDO SILVA OLIVEIRA')
insert into #nome values ('REJANE KELI JIROTO')
insert into #nome values ('RENATA CALORE')
insert into #nome values ('RENATO DE SOUZA SOGGIA')
insert into #nome values ('RIAN ALVES SOARES')
insert into #nome values ('RICARDO AIRES ABDALA')
insert into #nome values ('RICARDO BUENO DE CAMARGO ')
insert into #nome values ('RICARDO LUCIANO FURIGO')
insert into #nome values ('RICARDO MIGUEL DE OLIVEIRA GALLI')
insert into #nome values ('RITA  DE CASSIA ANTONIOLI')
insert into #nome values ('RITA CASSIA ANTONIOLI')
insert into #nome values ('RITA DE CASSIA VIEIRA')
insert into #nome values ('ROBERTA AFFONSO')
insert into #nome values ('ROBERTA FLAVIA DE OLIVEIRA')
insert into #nome values ('ROBERTO ALVES DE ANDRADE')
insert into #nome values ('ROBERTO DONIZETE FESTUCCIA')
insert into #nome values ('ROBERTO FERNANDO GALLO')
insert into #nome values ('ROBSON LUIZ RODRIGUES')
insert into #nome values ('RODOLFOL DA SILVA EUGENIO')
insert into #nome values ('RODRIGO CARLOS RODOWCIZ')
insert into #nome values ('RODRIGO CARLOS TOLENTINO')
insert into #nome values ('RODRIGO CESAR FRANCISCO ')
insert into #nome values ('RODRIGO FERREIRA MARQUES')
insert into #nome values ('RODRIGO JOSE DE CARVALHO NASCIMENTO')
insert into #nome values ('RODRIGO JOSE DI CARVALHO NASCIMENTO')
insert into #nome values ('RODRIGO JOSE TSUJI')
insert into #nome values ('RODRIGO LEANDRO  A. FELIX PEREIRA')
insert into #nome values ('RODRIGO LUIZ DA SILVA')
insert into #nome values ('ROGERIO MUNIZ PENHA')
insert into #nome values ('ROGERIO SORDI CAMPANINI')
insert into #nome values ('RONILDO AUGUSTO DE LIMA')
insert into #nome values ('ROSA APARECIDA DIAS')
insert into #nome values ('ROSA MARIA FERREIRA GONZALES ')
insert into #nome values ('ROSANA ALVES DE OLIVEIRA')
insert into #nome values ('ROSANE AFFONSO')
insert into #nome values ('ROSANGELA DUZZI GONCALVES')
insert into #nome values ('ROSANGELA GRATON')
insert into #nome values ('ROSANGELA PIRES PEREIRA')
insert into #nome values ('ROSELEIA PEREIRA')
insert into #nome values ('ROSELENA M. DA S. P. OTTOBONI')
insert into #nome values ('ROSELI GIRAO')
insert into #nome values ('ROSEMEIRE ANSANELLO')
insert into #nome values ('ROSEMEIRE APARECIDA ELIAS MARTINS')
insert into #nome values ('ROSEMEIRE GOMES DE SOUZA')
insert into #nome values ('ROSIANE CHIAROTI')
insert into #nome values ('ROSILENE MENEZES RIBEIRO')
insert into #nome values ('ROSIMARY APARECIDA PEDROSO LUIZ')
insert into #nome values ('ROSIMEIRE DA SILVA EUGENIO')
insert into #nome values ('ROSIMEIRE GONCALVES LINO')
insert into #nome values ('ROSINEA APARECIDA DO CARMO OLIVEIRA')
insert into #nome values ('RUTE NASCIMENTO DOS SANTOS')
insert into #nome values ('SABRINA LINO BORBA')
insert into #nome values ('SABRINA M. BORTOLIN')
insert into #nome values ('SALMA CURY JUNS')
insert into #nome values ('SAMUEL FRANCISCO DA COSTA')
insert into #nome values ('SAMUEL MAURO BAPTISTA')
insert into #nome values ('SANDRA APARECIDA MORAES DE OLIVEIRA')
insert into #nome values ('SANDRA DA MOTA SILVA')
insert into #nome values ('SANDRA MAJORE TESHEINER DAVINI')
insert into #nome values ('SANDRA MARIA ANIBALLI FERNANDEZ')
insert into #nome values ('SANDRA REGINA DOS SANTOS')
insert into #nome values ('SARA ESTEFANY OLIVEIRA DA SILVA')
insert into #nome values ('SARA FERNANDA ARO')
insert into #nome values ('SARA INGRID PEREIRA')
insert into #nome values ('SARAH FERNANDA ABRONISIO MORTOL')
insert into #nome values ('SAULO DE SOUSA')
insert into #nome values ('SEBASTIANA BELAMIRA BENTO DE OLIVEIRA')
insert into #nome values ('SERGIO APARECIDO DS SANTOS')
insert into #nome values ('SERGIO LUIS FERREIRA BALEA')
insert into #nome values ('SHEILA DA SILVA MACHADO ')
insert into #nome values ('SHEILA EMY SAITO')
insert into #nome values ('SIDNEIA CLAUDINO')
insert into #nome values ('SILVANA APARECIDA DA SILVA')
insert into #nome values ('SILVANA CARLA MARTIN ARROYO')
insert into #nome values ('SILVANA PERES')
insert into #nome values ('SILVANIA GONCALVES TORRES')
insert into #nome values ('SILVERIO JESUS DE OLIVEIRA')
insert into #nome values ('SILVIA HELENA GAIOTTO SALGADO')
insert into #nome values ('SILVIA HELENA MALAGUTI FEREIRA')
insert into #nome values ('SILVIA SPERGE')
insert into #nome values ('SILVIO LUIZ ROSSI JUNIOR')
insert into #nome values ('SIMONE APARECIDA RAMOS')
insert into #nome values ('SIMONE CHIRIELISON CAJUEIRO')
insert into #nome values ('SIMONE CORDEIRO DA SILVA')
insert into #nome values ('SIMONE DAMASIO BATISTA')
insert into #nome values ('SIRLENE  THEODORO DA SILVA')
insert into #nome values ('SIRLENE APARECIDA DA SILVA AUGUSTO')
insert into #nome values ('SOFIA ANELI ABDALA')
insert into #nome values ('SOLANGE GUIMARAES BARBOSA')
insert into #nome values ('SOLANGE ISIDORO DA SILVA')
insert into #nome values ('SONIA APARECIDA FRANCISCO ')
insert into #nome values ('SONIA CRISTINA BOSSA RIPA')
insert into #nome values ('SONIA PEREIRA DA GAMA')
insert into #nome values ('SORAIA CARVALHO DA SILVA NUNES')
insert into #nome values ('STEPHANIE MARQUES BARREIRO')
insert into #nome values ('STHEFANY CAROLINE ANUNCIO')
insert into #nome values ('SUELEN CRISTINA DIAS ')
insert into #nome values ('SUELI ANSELMO MENEZES')
insert into #nome values ('SUSANE FERNANDA  R FERRIRA')
insert into #nome values ('TACIANO GODOI DE SOUZA')
insert into #nome values ('TAINA ROBERTA ALVES')
insert into #nome values ('TAIS DOS REIS SILVA')
insert into #nome values ('TALITA MARISE BEZERRA')
insert into #nome values ('TALITA TAVARES DE JESUS')
insert into #nome values ('TALMO MIGUEL DA FONSECA ')
insert into #nome values ('TANIA MARIA CALIXTO')
insert into #nome values ('TANIA REGINA DOS SANTOS')
insert into #nome values ('TARSILIO PEREZ DE ARAUJO')
insert into #nome values ('TATIANA BATISTA MENDES')
insert into #nome values ('TATIANA CRISTINA DA COSTA')
insert into #nome values ('TAUANA PEREIRA ANUNCIO')
insert into #nome values ('TAUANE DE MELLO GOMES')
insert into #nome values ('TAYNARA KATIELLE DA SILVA')
insert into #nome values ('TERESA APARECIDA CARNIATO')
insert into #nome values ('THAIS ALVES DE MORAES')
insert into #nome values ('THAIS APARECIDA FERREIRA')
insert into #nome values ('THALITA GOMES CHINARELLO')
insert into #nome values ('THAMIRIS CRISTINA DE PAULA LINO OLIVEIRA')
insert into #nome values ('THEREZA CACILATO DIAS')
insert into #nome values ('THIAGO GIL MORTOL')
insert into #nome values ('THIAGO VINICIUS DE OLIVEIRA')
insert into #nome values ('TIAGO GOMES CHINARELLO')
insert into #nome values ('TIAGO LIMA DA SILVEIRA')
insert into #nome values ('TIAGO PIMENTA DE SOUZA')
insert into #nome values ('UEVERTON RIBEIRO SOUZA')
insert into #nome values ('VALCIR CHIQUITELLI')
insert into #nome values ('VALDEMIR APARECIDO FERREIRA')
insert into #nome values ('VALDIRENE APARECIDA DE OLIVEIRA')
insert into #nome values ('VALDO FERREIRA LUIZ')
insert into #nome values ('VALERIA CRISTINA VISQUETO BERTUOLO')
insert into #nome values ('VALERIA DE SOUZA')
insert into #nome values ('VANDER LUIZ CAMPOS LEITE FRARE')
insert into #nome values ('VANDERCI FURTADO')
insert into #nome values ('VANDERSON FERREIRA DOS SANTOS')
insert into #nome values ('VANDERSON MACIEL CARDOSO')
insert into #nome values ('VANESSA ALVES DOS SANTOS')
insert into #nome values ('VANESSA BITELLA FERREIRA')
insert into #nome values ('VANESSA CRISTINA COSTA')
insert into #nome values ('VANILDA MARIA DE ANDRADE')
insert into #nome values ('VERA LUCIA CAETANO LUIZ')
insert into #nome values ('VERA LUCIA DA SILVA')
insert into #nome values ('VERA LUCIA GARCIA')
insert into #nome values ('VERA LUCIA MARTINS DA SILVA')
insert into #nome values ('VERONICA THAIS CAMPOS BATISTA')
insert into #nome values ('VICTOR BRUNO ARCAS MENEGHINI')
insert into #nome values ('VICTOR FELIX DA SILVA')
insert into #nome values ('VICTOR GUSTAVO DOS SANTOS')
insert into #nome values ('VICTOR HUGO OLIVEIRA FERREIRA')
insert into #nome values ('VICTOR HUGO RIGOBELE SILVA')
insert into #nome values ('VICTORIA ALESSANDRA VIEIRA TEIXEIRA')
insert into #nome values ('VICTORIA BENVEGNU BACHEGA')
insert into #nome values ('VICTORIA RITA RODRIGUES LUZ')
insert into #nome values ('VILMA SILVA PEREIRA')
insert into #nome values ('VINICIUS AUGUSTO MENDONCA')
insert into #nome values ('VINICIUS FERNANDO PRADO RODRIGUES')
insert into #nome values ('VINICIUS LIMA DA SILVA SILVEIRA')
insert into #nome values ('VINICIUS MENEZES DE LIMA')
insert into #nome values ('VINICIUS ROMEIRO MERCHAN DOS SANTOS')
insert into #nome values ('VINICIUS SPERGE ESPIMADO')
insert into #nome values ('VINICIUS UBIDA OLIVEIRA')
insert into #nome values ('VIRLENE MARIA APARECIDA DE OLIVEIRA')
insert into #nome values ('VITORIA CAMILLI BARONI RIBEIRO')
insert into #nome values ('VIVIAN AMANDA BATISTA')
insert into #nome values ('VIVIANE CRISTINA ALVES')
insert into #nome values ('VIVIANE DA SILVA PEREIRA SANTOS')
insert into #nome values ('VIVIANE RODRIGUES PRADO ')
insert into #nome values ('WAGNER ALVERTO DA SILVA')
insert into #nome values ('WAGNER SOGGIA DA SILVA')
insert into #nome values ('WALTER LUIZ ESPAGNOL')
insert into #nome values ('WANDA MARIA DA SILVA FERNANDES')
insert into #nome values ('WANDERSON GONCALVES NORBERTO')
insert into #nome values ('WASHINGTON ANTONIO DA COSTA')
insert into #nome values ('WELLINGTON CANDIDO MANCIN')
insert into #nome values ('WELLINGTON DAVI MARTINS')
insert into #nome values ('WELLINGTON RAIMUNDO DE LACERDA')
insert into #nome values ('WENDELL JOSE BORTOLOTTI')
insert into #nome values ('WESLEY DE MORAIS')
insert into #nome values ('WESLEY DE MORAIS JUNIOR')
insert into #nome values ('WESLEY MENEZES DE LIMA')
insert into #nome values ('WILLIAN FERREIRA COSTA DA SILVA')
insert into #nome values ('WILLIAN PEDROSO LUIZ')
insert into #nome values ('WILLIAN TADEU MORILLO')
insert into #nome values ('YAGO GIL MORTOL')
insert into #nome values ('YASMIM CHRISTINA SILVA PEREIRA')
insert into #nome values ('YASMIM MOURA MARTINS')
insert into #nome values ('YASMIM SEVATO CAÇADOR LIMA')
insert into #nome values ('YASMIN VICTORIA A LIMA')
insert into #nome values ('YUTAKA SAITO')
insert into #nome values ('ZENEIDE LIMA DA SILVEIRA')
insert into #nome values ('ZILDA DA MATTA MARQUES')

*/

/*
insert into c values('a')
insert into c values(' ')
insert into c values('w')
insert into c values('b')
insert into c values('c')
insert into c values('d')
insert into c values('e')
insert into c values('f')
insert into c values('g')
insert into c values('h')
insert into c values('i')
insert into c values('j')
insert into c values('k')
insert into c values('l')
insert into c values('m')
insert into c values('n')
insert into c values('o')
insert into c values('p')
insert into c values('q')
insert into c values('r')
insert into c values('s')
insert into c values('t')
insert into c values('u')
insert into c values('v')
insert into c values('x')
insert into c values('z')
insert into c values('y')
insert into c values('z')
insert into c values('A')
insert into c values('Z')
insert into c values('ã')
insert into c values('Ã')
insert into c values('á')
insert into c values('Á')
insert into c values('à')
insert into c values('À')
insert into c values('â')
insert into c values('Â')
insert into c values('ä')
insert into c values('Ä')
insert into c values('é')
insert into c values('É')
insert into c values('è')
insert into c values('È')
insert into c values('ê')
insert into c values('Ê')
insert into c values('ë')
insert into c values('Ë')
insert into c values('Ú')
insert into c values('ú')
insert into c values('í')
insert into c values('Í')
insert into c values('ó')
insert into c values('Ó')
insert into c values('õ')
insert into c values('Õ')
insert into c values('ô')
insert into c values('Ô')
insert into c values('ö')
insert into c values('Ö')
insert into c values('ü')
insert into c values('Ü')
insert into c values('ñ')
insert into c values('Ñ')
insert into c values('ç')
insert into c values('Ç')
*/